### ISSUE TITLE
最新进展 （screenshot）

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#140]
#### 2019-06-30
- 支持多音质
- 改进 UI，补充文档，添加单元测试等

![image](https://user-images.githubusercontent.com/4962134/60396614-5ec62180-9b76-11e9-932e-1096f0cfe1c3.png)

#### 2019-05-19
- 确定插件机制 v1
- 添加配置模块
- 支持播放 MV

![image](https://user-images.githubusercontent.com/4962134/57981124-1b9c6d00-7a66-11e9-8218-6ec6c5196bc0.png)

#### 2018-06-25
- 大幅重写
- 详见 changelog.rst

![image](https://user-images.githubusercontent.com/4962134/41827460-2a38b370-7862-11e8-9195-24dd3987c4b3.png)

#### 2017-3-3
- 修复不能登录的问题

#### 2016-8-16
- 增加 歌手，专辑 描述信息

![image](https://cloud.githubusercontent.com/assets/4962134/17672685/235ae556-6350-11e6-98c6-1f18051e5da1.png)
#### 2016-8-15
- 增加图片缓存模块
- 在显示歌曲列表时，显示 Cover Image

![image](https://cloud.githubusercontent.com/assets/4962134/17650299/c12dc50c-627c-11e6-8056-bc705585873f.png)
#### 2016-8-4
- 在网易云音乐资源不存在的时候，尝试调用虾米资源
- 尝试让界面变得五颜六色

![image](https://cloud.githubusercontent.com/assets/4962134/17407088/9a20f8b2-5a98-11e6-8804-fcb8953e7ec9.png)
#### 2016-6-1
- 支持命令行控制，目前支持四个命令。`play`, `pause`, `next`, `previous`
  
  > echo -n "pause" | nc -4u -w0 localhost 8000
#### 2016-5-15
- 可以查看当前播放列表
- 可以拖动，将歌曲加入某个歌单中
- 右键歌曲，可以将歌曲加入当前播放列表
  **顺便提醒下，插件需要自己安装哦**
  ![Ubuntu 15.10](http://7xnn7w.com1.z0.glb.clouddn.com/new_2.png)
#### 2016-5-7
- 增加主题切换
- 修复 player 部分bug
  ![parallels picture](https://cloud.githubusercontent.com/assets/4962134/15092634/29f9a944-14a2-11e6-91d5-92cf4d3802d7.png)
#### 2016-5-6
- 考虑到各种问题，新的API 和 老的API 都在使用。（一个明显的好处就是：能听日语歌，也能听taylor swift，嘘...）
- 加了几个 状态栏 来标识程序现在的状态。
- 现在dev版本下载下来应该是能用的（网络稳定的话，基本不需要折腾）

![](http://7xnn7w.com1.z0.glb.clouddn.com/1.png)
#### 2016-5-2

（目前仍处于开发阶段，运行方法还没有文档说明）
<img width="1280" alt="screen shot 2016-05-02 at 20 42 26" src="https://cloud.githubusercontent.com/assets/4962134/14954631/8f9aca26-10a6-11e6-8eb3-88d673b598b4.png">

**Comment by M-Kepler** [comment]
你好，ubuntu16.04 执行`./install.sh`后无法打开，桌面已经有快捷方式了

**Comment by cosven** [comment]
@M-Kepler 
这个截图是开发版本，你需要下载 dev 分支的代码
然后 
```
cd FeelUOwn
make run
```

**Comment by BruceZhang1993** [comment]
开发版本有点小问题，登陆了网易云以后 单击头像 命令行似乎又做了一次登陆 且tooltip提示也是“登陆网易云音乐”
`[INFO] [nem.py line:78] : load last user.
[INFO] [nem.py line:108] : login in... set user infos.
[INFO] [connectionpool.py line:213] : Starting new HTTP connection (1): p3.music.126.net
[DEBUG] [connectionpool.py line:395] : "GET /CgokUBIcQBPEc_tATeyQPg==/7928578349746567.jpg HTTP/1.1" 200 11899
[INFO] [api.py line:50] : method=GET url=http://music.163.com/api/user/playlist/?offset=0&limit=200&uid=72417310 query=None
[INFO] [connectionpool.py line:213] : Starting new HTTP connection (1): music.163.com
[DEBUG] [connectionpool.py line:395] : "GET /api/user/playlist/?offset=0&limit=200&uid=72417310 HTTP/1.1" 200 None`

**Comment by cosven** [comment]
@BruceZhang1993 
恩，这个地方的确还有待完善。
我之前想的是：第二次点击头像，就弹出 **注销/登录另一个账户** 的对话框，但是没来得及做这个。

我想暂时就先改下 tooltip ，给用户一个提示好了，之后再去完善，因为个人感觉 **注销/登录另一个账户** 这个功能不太紧急。

**Comment by BruceZhang1993** [comment]
@cosven At least ~~ 新的api确实没有出现歌放不出的情况了
其他的慢慢完善就好

**Comment by LER0ever** [comment]
新版确实超级给力！大爱底部的那个类似于Vim Airline的状态条。
(只是暂时没有桌面歌词。。)

**Comment by wzdnzd** [comment]
而我还是喜欢以前的UI

**Comment by cosven** [comment]
以前的 UI 中的图标都是图片，而现在都是文字了，我觉得这是一个比较大的区别。
但是图标使用图片有几个缺点：设计难，操作难，更换难。但是相对可能比较美观。自己当初做的时候也是花了比较大的精力，结果还是萝卜青菜，各有所爱。后来想想：还不如用文字来代替图片，文字在技术人员这个人群众也是比较受欢迎的，于是就这样了。

不过话说回来，从整体布局来讲，感觉 UI 并没有很大的变化。@wzdnzd

**Comment by wzdnzd** [comment]
谢谢咯，试了一下新版，然后默默地换回了旧版的，新版的也很好，只是个人偏爱旧版的，辛苦了 @cosven

**Comment by cosven** [comment]
哈哈，之前也想到了很多人可能会不习惯，所以还开了一个 Issue 专门说明怎样回退到之前的版本。#144

**Comment by wzdnzd** [comment]
真的蛮不错的，辛苦了哈

**Comment by LER0ever** [comment]
@cosven 提几个小建议，

- 配色主题目前没有保存，下次启动还是Solarized

- 然后歌名建议进度条那儿也显示一下，要不然每次都要瞥最右下角。。

**Comment by carrjay** [comment]
我说刚更新，提示更新成功就没有下文了呢！

**Comment by sss132919** [comment]
放某些歌曲的时候，前面会出现乱七八糟的声音，然后才能听，但是时间已经过去了

2016-05-10 16:20 GMT+08:00 carrjay <notifications@github.com>:

**Comment by ker0491** [comment]
这个新版本 是不是没有歌词了？还是我没有找到呢？

**Comment by BruceZhang1993** [comment]
@LER0ever 配色的定义似乎在 feeluown/consts.py 可以试着手动改～ 歌名的位置确实不够醒目的说

**Comment by zhixiangjoy** [comment]
作者，你好，歌曲没有收藏功能啊？

**Comment by cosven** [comment]
`可以拖动，将歌曲加入某个歌单中`
这个是你需要的功能么？

**Comment by wzdnzd** [comment]
网易云音乐出官方linux版了，可能以后用feeluown的人就慢慢减少了，以后更新的动力还足么？ @cosven

**Comment by cosven** [comment]
一句话总结：会更新，更新的功能更趋向炫酷，面向对象由大众逐渐转向 developer。

有兴趣可以阅读下文：

实际上，今年年初开发第二个版本的时候我就纠结过这个问题，当时我知道 Deepin 在开发网易云音乐（其实去年8月份，这个项目就谈下来了，当时计划是2015年底开发好...），我想有了官方版，用户肯定少很多，或者说几乎没几个。那到底要不要开发，考虑了个把月，最后又动手了。

大概有下面几个理由：
- 当时官方版还没出来。（这个原因在当时还是很重要的）
- 我笔记本是 MacbookPro，但是我用官方版用的较少，主要体现在 快捷键和可定制化方面把，作为一名开发者，表示有点不服啊（程序员的怪癖）
- 然后，feeluown 从一开始就把 网易云音乐 当成一个插件。 
- feeluown 是对开发者友好的一款 app。**这是最根本的把...**

其实话说回来，有了官方版之后。我可以把更多的精力放在开发一些 开发者喜欢的**新特性** 上了，开发起来更加大胆了。
比如说：支持多语言插件系统；支持远程控制；更多的命令行交互控制。在之前，这些功能都只能 放到TODO 列表的末端。

**Comment by wzdnzd** [comment]
@cosven 哈哈，给你点赞

**Comment by hwding** [comment]
@cosven 下载的歌曲存在那里, 貌似没找到...
@wzdnzd 网易云音乐的官方Linux版貌似是deb啊, SuSE哭晕...

**Comment by wzdnzd** [comment]
@hwding 这个一般都可以解压 然后把文件复制到相应目录下 或者用alien将deb转为rpm

**Comment by hwding** [comment]
SuSE的包管理貌似搜索不到alien这个玩意...

**Comment by cosven** [comment]
据说过几天就会有 RPM 包呢，微博上看的。@hwding

**Comment by hwding** [comment]
不用啦😂，还是feeluown逼格高，为了维护开发程序猿的尊严果断放弃官方版😏
@cosven

**Comment by BruceZhang1993** [comment]
@cosven 继续支持，官方版本我这边ArchLinux出现内存泄露的情况～

**Comment by hwding** [comment]
@BruceZhang1993
archlinux大神求安装指导😐

**Comment by BruceZhang1993** [comment]
@hwding AUR里面有的说～～

**Comment by wangjiezhe** [comment]
试用了一下官方版，结果直接内存直接耗尽，所以还是回来吧￼￼

**Comment by LER0ever** [comment]
Manjaro 官方版放了一会闪退。。继续来支持FeelUOwn
毕竟没有人想开着个chromium引擎听音乐，实在太烧资源了。。。

**Comment by cosven** [comment]
毕设论文提交最后两天，我要写论文了...6 月份再来修 bug

**Comment by wzdnzd** [comment]
原来你也大四。。。@cosven

**Comment by cosven** [comment]
是啊，要死了 -. - 程序没写好，论文还没开始。

**Comment by wzdnzd** [comment]
我们6月10号左右也要交毕业论文了。。。话说，你毕设也是软件开发？

**Comment by cosven** [comment]
做数据可视化(叙事可视化)（很低端的那种），应该不算软件开发。
如果是软件开发的话，我就直接拿这个去了（苦笑）

**Comment by hwding** [comment]
老天, 全是前辈阿...
我只有大一

**Comment by wzdnzd** [comment]
难道只有我看着数据可视化的那个图特别炫酷么？(。_。)  我还在做算法研究，会不会更低端。。。

**Comment by cosven** [comment]
- 当我第一次听说毕设只要一星期的时候
- 其实我是，是不相信的
- 毕设怎么会那么水
- 学长跟我讲，3天程序4天论文，很水、很水、很水
- 毕设 duang duang duang 就完了
- 后来我经过、也知道 这就是真的，真的这么水

>....<

**Comment by cosven** [comment]
可视化这个研究方向是厉害。
只是我做的东西 将会 比较水（我自己太水了...）

**Comment by wzdnzd** [comment]
适合数据挖掘和分析方向\(^o^)/~  大数据需要你

**Comment by cosven** [comment]
哈哈，我要去赶论文，程序了 T_T

**Comment by cosven** [comment]
master 分支：支持命令行控制。f02774af42beab0ec6bb31a5d5ba67e389084255

**Comment by haulm** [comment]
5 月集成到 osolinux 中，今天更新了一下可以拖放音乐了，搜索空字串闪退的问题也修正了，赞一个。

**Comment by cosven** [comment]
- [x] 在网易云音乐资源不存在的时候，尝试调用虾米资源

对 五颜六色 的界面做了一些初步的尝试。

**Comment by redapple0204** [comment]
@cosven 其实嘛，网易云官方最大的缺点就是依赖包版本要求较高，导致了一些debian stable版本和较老发行版的用户无法安装，所以本项目还是很受欢迎的。

**Comment by cosven** [comment]
- [x] 在 artist 页面和 album 页面相应的显示 artist 描述和 album 描述
- [x] 显示歌单封面等

**Comment by cosven** [comment]
是嘛，感觉除了官方版之后，用这个的比较少了。之前都会碰到大家提各种奇奇怪怪、大大小小的问题，现在基本我按照自己兴趣开发就好了....

**Comment by joylin1984** [comment]
你好，你的app真的很炫酷。作为pyqt初学者，真的很仰慕你。
希望作者能考虑下，写文章说说到底如何让pyqt程序，有这么高的颜值啊。
使用样式表吗。还是别的什么技巧。
可能我是小白，阅读代码还有点难度，期待作者，能以这个项目示例，介绍自己的开发经验。 @cosven

**Comment by cosven** [comment]
@joylin1984 你可以看看[这个东西](https://github.com/cosven/cosven.github.io/issues/41)，算是半个总结。这个没什么技术细节，都是一些概括性的东西。

你可以在评论下直接提一下问题，如果能解答的话，我一定尽力说明白，或者推荐一些参考资料，或者谈谈心路历程。

**Comment by doubleseoo** [comment]
我的哥，厉害，佩服

**Comment by 1dot75cm** [comment]
赞，最近也在学 PyQt，写了个小工具 [repo-checker](https://github.com/1dot75cm/repo-checker)。 打算研究一下大神的代码 @cosven

**Comment by SuperSuperSuperSuper5** [comment]
@1dot75cm 看了一下，哎呦不错哦！

**Comment by 1dot75cm** [comment]
欢迎莅临指导 @SuperSuperSuperSuper5
