### ISSUE TITLE
关于插件：安装和编写

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#148]
> **UPDATE 2019-05-19**: feeluown 3.0 支持了新的插件发现机制，原理可以参考 [python packaging 文档](https://packaging.python.org/guides/creating-and-discovering-plugins/)。例子可以参考 [feeluown-netease](https://github.com/feeluown/feeluown-netease) 或者 [feeluown-local](https://github.com/feeluown/feeluown-local) 等。

#### 已知的可用插件，大家可以自己安装使用
- [mpris2 插件](https://github.com/cosven/feeluown-mpris2-plugin.git)
- [mac hotkey 插件](https://github.com/cosven/feeluown-mac-hotkey-plugin)

在这个新版本中，各种插件都需要 **自己动手安装** 。

现在我个人编写了三个插件：
- https://github.com/cosven/feeluown-mpris2-plugin.git mpris2 插件，linux 用户可用
- neteasemusic 目前这个插件是附带在FeelUOwn软件包中的，这是为了让用户过渡更加流畅。（之后会把它移除，单独为它建一个 repo）
##### 插件的安装使用

下载插件包，把插件包放在 `~/.FeelUOwn/plugins` 目录下即可。下次重启软件时就会自动加载。（等软件完善之后，可以不需要重启）
#### 插件开发

这次重新开发新版本，对**怎样更容易的开发插件**还是有着重考虑的。因为之前发现，大家写插件的激情不够，或者说根本没有（苦笑脸），我反思下，一方面，没有插件开发文档，没有教程。另一方面，代码架构不好，编写难度太高。（其实原因还有很多啦...）
###### 插件示例

一个简单插件的示例：https://github.com/cosven/feeluown-mpris2-plugin.git
一个复杂插件的示例：参考 https://github.com/cosven/FeelUOwn/tree/master/feeluown/plugins/neteasemusic
##### 怎样编写一个插件

编写一个插件，说难不难，说容易嘛，个人感觉真的挺容易。不过你要会 编程 ^_^。如果你会 Python，那么编写一个简单地插件简直易如反掌。我没吹...

一个插件其实就是一个 Python Package。这个 Package 的结构大概是这样。

```
.
├── __init__.py
├── README.md
└── xxx.py
```

你需要在 `__init__.py` 中实现5个东西，它们是三个变量，和两个函数。三个变量分别是：`__alias__`，`__version__`，`__desc__`。两个函数就是：`enable(app)`，`disable(app)`。

下面是一个最简单的插件示例

```
# __init__.py


__alias__ = 'demo'
__version__ = '0.0.1'
__desc__ = 'demo description'

def enable(app):
    # do something
    pass

def disable(app):
     pass
```

**Comment by zhang19960118** [comment]
赞！

**Comment by SuperSuperSuperSuper5** [comment]
赞！

**Comment by Siffre** [comment]
大神，能加个QQ咨询一下吗？ 我的952974923  验证：google
