### ISSUE TITLE
极为勉强的打了个deb包

### ISSUE THREAD

**Issue by redapple0204** [feeluown/FeelUOwn#211]
[feeluown_9.3_all.zip](https://github.com/cosven/FeelUOwn/files/629435/feeluown_9.3_all.zip)
打开后输入sudo python3 /opt/feeluown/setup.py 才能用...
论作者能不能写个python直接打开程序主窗口而不需要调用到安装脚本？
@cosven

**Comment by redapple0204** [comment]
似乎找到了另外的办法，请稍等...

**Comment by JadeVane** [comment]
@redapple0204 等了一年多啦，deb包怎样了

**Comment by cosven** [comment]
等了两年啦，哈哈哈

感谢感谢 ~

**Comment by cosven** [comment]
先 close 拉 ~
