### ISSUE TITLE
Non-C locale detected, this is not support

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#246]
启动时报错：
```
Non-C locale detected, this is not support
Call `setlocal(LC_NUMERIC, "C")` in your code
```

在终端中运行 `locale` 命令输出为：
```
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=zh_CN.UTF-8
```

**Comment by cosven** [comment]
About LC_NUMERIC: https://help.ubuntu.com/community/Locale

**Comment by cyliuu** [comment]
> About LC_NUMERIC: https://help.ubuntu.com/community/Locale

有个建议，这段代码其实可以移到mpv.py里面，参考: https://pypi.org/project/python-mpv/

**Comment by cosven** [comment]
> 有个建议，这段代码其实可以移到mpv.py里面，参考: https://pypi.org/project/python-mpv/

嗯，理论上这个可以尽量往下层移。
python-mpv 确实在[最新版](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L38)中修复了这个问题，得找个时间把 feeluown-core 依赖的 mpv.py 更新一下（TODO 只增不减...
