### ISSUE TITLE
国外用户可能无法正常使用？

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#250]
详情可见 #249

**Comment by hengstchon** [comment]
海外用户表示，不登录情况下，可以正常使用 QQ 音乐，虾米音乐可以登录，网易云音乐或许由于 GDPR 条款（有关欧洲隐私）无法登录。虾米音乐登录后也可以正常使用。

**Comment by hengstchon** [comment]
添加了网易云的 `103.18.208.222 m8.music.126.net` 这条 host 后也不管用，可能需要找其他host。

**Comment by cosven** [comment]
> 添加了网易云的 `103.18.208.222 m8.music.126.net` 这条 host 后也不管用，可能需要找其他host。

我有几个小问题

1. 能 ping 通 music.163.com 吗？感觉应该能，我用 [check-host 测试了下](https://check-host.net/check-http?host=music.163.com/weapi)
2. 能登录成功吗？

如果第一个能，而第二个不能，说明网易云可以 block 了部分地区的 IP，这时候可以考虑使用代理（找一个国内 IP）。可以 Google 搜免费代理等。

1. 如果能登录成功，但是无法播放音乐

说明（我猜测）网易云的 CDN block 了部分地区 IP，同样的，可以考虑使用代理（让自己换一个 IP）。或者给 CDN 域名绑定 host（使用特定的 CDN 节点）。

**Comment by hengstchon** [comment]
1. 能 ping 通。
2. 客户端不能登录，网页端我用了一个 chrome 插件，看了下，里面主要是在 requestHeaders 里增加了一个键为 'X-Real-IP' 的国内 ip 地址。

还在摸索怎样给它加代理……

**Comment by hengstchon** [comment]
最后我把代码 clone 到本地，然后把 `fuo-netease` 插件放到 Plugins 文件夹，在 api 的 headers 里加了个 'X-Real-IP'， 就成功登录了，歌单能显示，歌曲也能播放。

请问这个能做成一个海外用户的选项功能集成到包里去吗？

PS：大佬你的文档太少了，摸索了好半天……不过好在最后成功了。

**Comment by cosven** [comment]
emmm，你说哪个方面的文档？...插件目前基本都没有文档 =。=

ummm，我感觉你可以暂时这样处理 `X-Real-Ip` 这个选项，在 `.fuorc` 配置文件里面加入这么几行代码：

```python
def update_netease_request_headers(*args, **kwargs):
    from fuo_netease import provider

    provider.api.headers.update({'X-Real-Ip': '...'})


when('app.initialized', update_netease_request_headers)
```

**Comment by hengstchon** [comment]
可能是我太弱了吧，当时我把插件 git clone 下来后，不知道怎样拼接到主程序里去，也没找到文档，然后看代码琢磨了一会。

在 `~/.fuorc` 里加了上面这个代码断后，就可以正常使用网易云了，感谢大佬耐心解答！

**Comment by cosven** [comment]
> 可能是我太弱了吧，当时我把插件 git clone 下来后，不知道怎样拼接到主程序里去，也没找到文档，然后看代码琢磨了一会。
> 
> 在 `~/.fuorc` 里加了上面这个代码断后，就可以正常使用网易云了，感谢大佬耐心解答！

我的锅，应该是之前插件模块没有写文档 ~
