### ISSUE TITLE
打包了一个AppImage

### ISSUE THREAD

**Issue by coslyk** [feeluown/FeelUOwn#261]
下载：https://github.com/coslyk/AppImageCollection/releases/download/init/FeelUOwn-3.1.1-x86_64.AppImage
生成配置在这里：https://github.com/coslyk/AppImageCollection/blob/master/feeluown/feeluown.yml
欢迎测试反馈～

**Comment by cosven** [comment]
在 Ubuntu 18.04 下测试是可以正常工作的。
感谢~

**Comment by cosven** [comment]
不过有个问题，这样打包之后，使用命令行的正确姿势是怎样的呢？

我看现在可以这样子运行，但不知道最佳实践是怎样的

```
cosven@ubuntu:~$ ./FeelUOwn-3.0a5-x86_64.AppImage status
repeat:    1
random:    0
volume:    100
state:     playing
duration:  255.085714
position:  23.96456958730182
song:      fuo://netease/songs/5054926	# When You Say Noth… - Ronan Keating
lyric-s:   Without saying a word,
```

**Comment by mengyaoss77** [comment]
appimage下载地址404了

**Comment by cosven** [comment]
你看项目 README 中有最新版 3.0a6 https://github.com/coslyk/AppImageCollection/

**Comment by cosven** [comment]
大宝相关内容都放在 #313 跟进。
