### ISSUE TITLE
macos 上无法安装

### ISSUE THREAD

**Issue by yefeiyu** [feeluown/FeelUOwn#276]
localhost:bin charlesthomas$ pip install 'feeluown>=3.0[battery,macos]' --upgrade --user
ERROR: Invalid requirement: 'feeluown>=3.0[battery,macos]'

开始时用手册方法：
`$ pip install feeluown>=3.0[battery,macos] --upgrade --user`
然后直接：
`$ pip install feeluown`
但运行时出错：
```
$ fuo status
Traceback (most recent call last):
  File "/Users/charlesthomas/.pyenv/versions/xenv/bin/fuo", line 6, in <module>
    from feeluown.__main__ import main
  File "/Users/charlesthomas/.pyenv/versions/anaconda3-2019.03/envs/xenv/lib/python3.7/site-packages/feeluown/__main__.py", line 11, in <module>
    from fuocore.dispatch import Signal
  File "/Users/charlesthomas/.pyenv/versions/anaconda3-2019.03/envs/xenv/lib/python3.7/site-packages/fuocore/__init__.py", line 2, in <module>
    from fuocore.player import (
  File "/Users/charlesthomas/.pyenv/versions/anaconda3-2019.03/envs/xenv/lib/python3.7/site-packages/fuocore/player.py", line 385, in <module>
    from fuocore.mpvplayer import MpvPlayer  # noqa: F841, F401
  File "/Users/charlesthomas/.pyenv/versions/anaconda3-2019.03/envs/xenv/lib/python3.7/site-packages/fuocore/mpvplayer.py", line 4, in <module>
    from mpv import (
  File "/Users/charlesthomas/.pyenv/versions/anaconda3-2019.03/envs/xenv/lib/python3.7/site-packages/mpv.py", line 50, in <module>
    raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, maybe consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
```
删除却无法彻底删除。在`.local/bin`里还有三个文件。

再次使用手册安装还是出错：
`pip install feeluown>=3.0[battery,macos] --upgrade --user`
```
  WARNING: The scripts feeluown, feeluown-genicon and fuo are installed in '/Users/aa/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

**Comment by hengstchon** [comment]
用这条命令，亲测可以。
`pip3 install 'feeluown[battery,macos]>=3.0.1' --user -i https://pypi.org/simple/`

**Comment by cosven** [comment]
LZ 是没有安装 mpv 吧？
可以运行下面命令，然后再试试 ~ （ps: 下面这个安装时间可能比较久）
```
brew install mpv
```

**Comment by yefeiyu** [comment]
我安装了一个python环境，位置是`.pyenv/versions/xenv/bin/`
现在在按手册安装feeluown，安装的部件并没有安装到（并使用）上述路径，而是在`~/.local`下生成`bin, lib` and python文件夹。
导致后面的错误。

**Comment by yefeiyu** [comment]
```
Installing collected packages: marshmallow, fuo-qqmusic, fuo-xiami, mutagen, fuzzywuzzy, fuo-local, soupsieve, beautifulsoup4, fuo-netease, pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-Quartz, feeluown
  WARNING: The scripts feeluown, feeluown-genicon and fuo are installed in '/Users/charlesthomas/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed beautifulsoup4-4.7.1 feeluown-3.0.1 fuo-local-0.1.2 fuo-netease-0.2 fuo-qqmusic-0.1.3 fuo-xiami-0.1.2 fuzzywuzzy-0.17.0 marshmallow-2.19.5 mutagen-1.42.0 pyobjc-core-5.2 pyobjc-framework-Cocoa-5.2 pyobjc-framework-Quartz-5.2 soupsieve-1.9.2
```

**Comment by cosven** [comment]
我看这个报错说的就是你没有安装 mpv，你安装了吗？ @yefeiyu

我之前在上面评论了：https://github.com/feeluown/FeelUOwn/issues/276#issuecomment-507181972

**Comment by cosven** [comment]
> 这条命令依然出错。
> `pip3 install 'feeluown[battery,macos]>=3.0.1' --user -i https://pypi.org/simple/`
> 
> ```
> Installing collected packages: marshmallow, fuo-qqmusic, fuo-xiami, mutagen, fuzzywuzzy, fuo-local, soupsieve, beautifulsoup4, fuo-netease, pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-Quartz, feeluown
>   WARNING: The scripts feeluown, feeluown-genicon and fuo are installed in '/Users/charlesthomas/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> Successfully installed beautifulsoup4-4.7.1 feeluown-3.0.1 fuo-local-0.1.2 fuo-netease-0.2 fuo-qqmusic-0.1.3 fuo-xiami-0.1.2 fuzzywuzzy-0.17.0 marshmallow-2.19.5 mutagen-1.42.0 pyobjc-core-5.2 pyobjc-framework-Cocoa-5.2 pyobjc-framework-Quartz-5.2 soupsieve-1.9.2
> ```

这个是正常的，没啥问题，它只是警告你没有把 `~/.local/bin` 加到 PATH 中去。

> 
> `$ fuo `
> 
> ```
> Traceback (most recent call last):
>   File "/Users/charlesthomas/.pyenv/versions/xenv/bin/fuo", line 6, in <module>
>     from feeluown.__main__ import main
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/feeluown/__main__.py", line 11, in <module>
>     from fuocore.dispatch import Signal
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/fuocore/__init__.py", line 2, in <module>
>     from fuocore.player import (
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/fuocore/player.py", line 385, in <module>
>     from fuocore.mpvplayer import MpvPlayer  # noqa: F841, F401
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/fuocore/mpvplayer.py", line 4, in <module>
>     from mpv import (
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/mpv.py", line 50, in <module>
>     raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
> OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, maybe consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
> ```

后面这个出错的原因就是我上面说的，没有安装 mpv

**Comment by cosven** [comment]
> 这条命令依然出错。
> `pip3 install 'feeluown[battery,macos]>=3.0.1' --user -i https://pypi.org/simple/`
> 
> ```
> Installing collected packages: marshmallow, fuo-qqmusic, fuo-xiami, mutagen, fuzzywuzzy, fuo-local, soupsieve, beautifulsoup4, fuo-netease, pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-Quartz, feeluown
>   WARNING: The scripts feeluown, feeluown-genicon and fuo are installed in '/Users/charlesthomas/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> Successfully installed beautifulsoup4-4.7.1 feeluown-3.0.1 fuo-local-0.1.2 fuo-netease-0.2 fuo-qqmusic-0.1.3 fuo-xiami-0.1.2 fuzzywuzzy-0.17.0 marshmallow-2.19.5 mutagen-1.42.0 pyobjc-core-5.2 pyobjc-framework-Cocoa-5.2 pyobjc-framework-Quartz-5.2 soupsieve-1.9.2
> ```

这个是正常的，没啥问题，它只是警告你没有把 `~/.local/bin` 加到 PATH 中去。

> 
> `$ fuo `
> 
> ```
> Traceback (most recent call last):
>   File "/Users/charlesthomas/.pyenv/versions/xenv/bin/fuo", line 6, in <module>
>     from feeluown.__main__ import main
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/feeluown/__main__.py", line 11, in <module>
>     from fuocore.dispatch import Signal
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/fuocore/__init__.py", line 2, in <module>
>     from fuocore.player import (
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/fuocore/player.py", line 385, in <module>
>     from fuocore.mpvplayer import MpvPlayer  # noqa: F841, F401
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/fuocore/mpvplayer.py", line 4, in <module>
>     from mpv import (
>   File "/Users/charlesthomas/.local/lib/python3.7/site-packages/mpv.py", line 50, in <module>
>     raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
> OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, maybe consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
> ```

后面这个出错的原因就是我上面说的，没有安装 mpv

**Comment by cosven** [comment]
hi ~ 想了解下，后来安装成功了吗？ @yefeiyu

**Comment by 5kbpers** [comment]
遇到了同样的问题，运行 `brew link --overwrite mpv` 就可以了 @yefeiyu
