### ISSUE TITLE
使用QQ音乐的话不需要登录吗？ 

### ISSUE THREAD

**Issue by CamosiWANG** [feeluown/FeelUOwn#278]
在用QQ音乐的时候，为什么没有登录界面，我没办法查看我自己的歌单。

**Comment by cosven** [comment]
QQ 音乐插件对应的项目地址在这里：https://github.com/feeluown/feeluown-qqmusic

目前它支持搜索，不支持登录 QQ 音乐，所以你没找到登录界面，而网易云和虾米是有的...
