### ISSUE TITLE
Ubuntu 16.04 安装成功后无法播放音乐

### ISSUE THREAD

**Issue by HBaaa** [feeluown/FeelUOwn#285]
获取列表到时没有问题但是无论是本地还是网络歌曲都是无法播放的
显示的提示内容为AttributeError: ('mpv property does not exist', -8, (<MpvHandle object at 0x7f0006b81400>, b'ytdl-format', b''))

**Comment by cosven** [comment]
目前**猜测**可能有两个原因：
1. libmpv 版本比较低（或者高）导致的
2. 你的 libmpv 没有安装 youtube-dl 的支持（根据我自己的经验，一般的 libmpv 都是有 youtube-dl 支持的）

但要确认问题，还需要更多的信息，你可以提供一下下面这些信息吗？
1. 操作系统（发行版）及其版本（比如 Ubuntu 16.04）
2. mpv 版本（比如通过 mpv --version，可以查看 mpv 版本）

**Comment by HBaaa** [comment]
![mpv版本信息](https://i.loli.net/2019/07/29/5d3e5b96ccf1221524.png)
我使用的是Ubuntu16.04

**Comment by HBaaa** [comment]
使用的版本为feeluown的3.0.1版本

**Comment by cosven** [comment]
> ![mpv版本信息](https://camo.githubusercontent.com/44909c953452d5c4c8f357db39a2b1976869d165/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30372f32392f3564336535623936636366313232313532342e706e67)
> 我使用的是Ubuntu16.04

我感觉可以升级一下 libmpv(mpv) 版本，最新版的已经是 0.29 了，我猜很可能是因为目前你系统上的 mpv 版本太低。

我搜了搜，比如这个升级方法：http://ubuntuhandbook.org/index.php/2016/07/install-mpv-media-player-ubuntu-16-04/

**Comment by HBaaa** [comment]
好的，谢谢，我也是刚看到，在18年都已经是0.29版本了，我会在尝试后进行答复，谢谢你的帮助

**Comment by HBaaa** [comment]
> > ![MPV版本信息](https://camo.githubusercontent.com/44909c953452d5c4c8f357db39a2b1976869d165/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30372f32392f3564336535623936636366313232313532342e706e67)
> > 我使用的是Ubuntu16.04
> 
> 我感觉可以升级一下libmpv（mpv）版本，最新版的已经是0.29了，我猜很可能是因为目前你系统上的mpv版本太低。
> 
> 我搜了搜，比如这个升级方法：[http](http://ubuntuhandbook.org/index.php/2016/07/install-mpv-media-player-ubuntu-16-04/)：[//ubuntuhandbook.org/index.php/2016/07/install-mpv-media-player-ubuntu-16-04/](http://ubuntuhandbook.org/index.php/2016/07/install-mpv-media-player-ubuntu-16-04/)

我进行了更新，但是依然还是同样的错误。
我能退回到之前的2.3版本吗？我之前使用那个版本未出现问题

**Comment by HBaaa** [comment]
很尴尬，已经解决问题了，我在添加ppa之后安装mpv，直接尝试了，我检查更新之后安装了更新，已经好了。
很感谢您的帮助。

**Comment by cosven** [comment]
不用谢，应该的 ~

我想想可能应该在 FeelUOwn 启动时，判断一下 libmpv 版本，太低的时候，给用户一个提示。

**Comment by abananajuice** [comment]
貌似ubuntu都会遇到这个问题，因为我的也播放不了（⊙ｏ⊙）

**Comment by cosven** [comment]
> 貌似ubuntu都会遇到这个问题，因为我的也播放不了（⊙ｏ⊙）

相对新版的 Ubuntu(比如 18.04) 应该没有这个问题，老版本的（比如 16.04）应该是肯定会遇到这个问题。如果你觉得需要的话，可以新建一个 issue，我们一起看看怎样解决，以及问题的原因是什么。

**Comment by abananajuice** [comment]
> > 貌似的ubuntu都会遇到这个问题，因为我的也播放不了（⊙o⊙）
> 
> 相对新版的Ubuntu（比如18.04）应该没有这个问题，老版本的（比如16.04）应该是肯定会遇到这个问题。
> 
> ps：如果你觉得需要的话，可以新建一个问题，我们一起看看怎样解决，以及问题的原因是什么。

刚刚我也解决了问题，确实是libmpv的版本太低。
