### ISSUE TITLE
可以考虑appimage打包吗？

### ISSUE THREAD

**Issue by sss132919** [feeluown/FeelUOwn#293]
可以考虑appimage打包吗？

**Comment by cosven** [comment]
TL;DR, 我很想这样做，但是短期没有足够的时间来尝试和测试。如果你有兴趣进行打包，我会提供力所能及的帮助。

我在[这个 issue](https://github.com/feeluown/FeelUOwn/issues/261) 看到之前有朋友尝试过 appimage 打包，并且成功了，所以从理论上来讲，这个方案是可行的。

而个人对 Python 的包管理、分发等技术比较熟悉，所以目前选用的打包方案是将代码打包成一个 Python 包，放在 pypi 上，选择这个自己熟悉的方案有好有坏。好处是我可以保证它可以及时更新，并且尽可能保证它的稳定性；不足是这可能要求使用者对 pip 等 Python 包管理工具有一定的了解等。

**Comment by cosven** [comment]
先暂时关闭这个 issue 啦 ~
