### ISSUE TITLE
Mac 系统执行 example 的 mpv脚本报错

### ISSUE THREAD

**Issue by albertofwb** [feeluown/FeelUOwn#295]
commit：b56e544
![image](https://user-images.githubusercontent.com/5900716/65433110-fc1bb380-de4e-11e9-9c26-5dd16c546682.png)

opengl 版本
pyopengl-3.1.0

执行 `mpv data/test.webm`可正常播放测试文件

**Comment by cosven** [comment]
怀疑是 locale 设置的问题，但目前我也不是特别确认。

你可以尝试先 `export LC_ALL=C` 或者 `export LC_NUMERIC=C` 然后运行这个 mpv_qtwidget_opengl.py 试试。

另外，你可以把你的 `locale` 命令的输出贴出来看看嘛？

```
🐍 ~/c/feeluown master* > locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by cosven** [comment]
阅读了一下这个 issue https://github.com/mpv-player/mpv/issues/1491，它大概是说 QT App 初始化的时候会设置部分 locale。

所以在我们这个场景中，我们可以尝试在初始化 Qt Application 之后再设置这个 locale。方法是把这两行调换一下位置

https://github.com/feeluown/FeelUOwn/blob/b56e544de549a69e29947266b65354b266e9d922/research/mpv_qtwidget_opengl.py#L82-L83

**Comment by albertofwb** [comment]
> 阅读了一下这个 issue [https://github.com/mpv-player/mpv/issues/1491，它大概是说](https://github.com/mpv-player/mpv/issues/1491%EF%BC%8C%E5%AE%83%E5%A4%A7%E6%A6%82%E6%98%AF%E8%AF%B4) QT App 初始化的时候会设置部分 locale。
> 
> 所以在我们这个场景中，我们可以尝试在初始化 Qt Application 之后再设置这个 locale。方法是把这两行调换一下位置
> 
> https://github.com/feeluown/FeelUOwn/blob/b56e544de549a69e29947266b65354b266e9d922/research/mpv_qtwidget_opengl.py#L82-L83

这两行代码位置调换之后，可以成功运行并播放动画了。

原因在你提到的  [issue](https://github.com/mpv-player/mpv/issues/1491#issuecomment-70541170)有说明
