### ISSUE TITLE
mpv property does not exist

### ISSUE THREAD

**Issue by Yanghua2018** [feeluown/FeelUOwn#301]
Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fuocore.player import MpvPlayer
>>> player =MpvPlayer()
>>> player.initialize()
>>> player.play('/home/ezlab/.FeelUOwn/songs/test.mp3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ezlab/workdir/app/FeelUOwn/fuocore/mpvplayer.py", line 81, in play
    _mpv_set_property_string(self._mpv.handle, b'ytdl-format', b'')
  File "/home/ezlab/workdir/app/FeelUOwn/mpv.py", line 110, in raise_for_ec
    raise ex(ec, *args)
AttributeError: ('mpv property does not exist', -8, (<MpvHandle object at 0x7f1145ce5240>, b'ytdl-format', b''))
>>>

**Comment by cosven** [comment]
目前怀疑是由于 libmpv 版本过高或者过低，导致一些接口使用上有一些变化。

你可以提供一下以下几个信息吗？
1. Linux 发行版（比如 Ubuntu 18.04 等）
2. feeluown 的版本，可以通过 `feeluown -V` 来获取
3. libmpv 的版本，可以通过这样一段代码来获取
```python
import mpv
mpv._mpv_client_api_version()
```
3. mpv 的版本，可以通过 `mpv --version` 来获取（如果安装了 mpv 的话，没安装的话就忽略这个步骤）

**Comment by cosven** [comment]
你好，这个问题后来解决了吗？
