### ISSUE TITLE
增加 fm模式

### ISSUE THREAD

**Issue by wuliaotc** [feeluown/FeelUOwn#315]
- 作者：@wuliaotc
- 创建时间：2020-02-01
- 最近更新：2020-02-01 18:00
- 最新状态：
  - *2020-02-1* - 提出简单的想法

## 简介与背景
为增加fm模式,feeluown还需要一些新特性
## 方案概述
1. 增加fm模式, left panel 部分无tableView,显示背景图片

- [x] playlist支持锁定为顺序播放

- [x] playlist支持歌单锁定,即此时不可外部添加歌曲(自己本身可以加)

- [x] playlist可以发送playlist eof信号

- [ ] provider需要能够向feeluown的playlists中添加歌曲

2. 如果需要增加fm模式的left_panel部分的tableviwer

- [ ] 包括特定的left_panel fm listview

- [ ] 需要支持FMPlaylist 与playlist的绑定

- [ ] 需要支持FMPlaylist 能够获取playlist的播放状态,以便自动获取新的歌曲

**Comment by cosven** [comment]
> - [ ] playlist支持锁定为顺序播放
- [ ] playlist支持歌单锁定,即此时不可外部添加歌曲(自己本身可以加)
- [ ] playlist可以发送playlist eof信号

这三个可以算作是 Player/Playlist 这一模块的事情。

> - [ ] provider需要能够向feeluown的playlists中添加歌曲

这个可能算是“非 Player/Playlist 模块”的事情。

这两个模块怎么交互，我觉得我们还可以具体一些。因为模块交互的地方通常涉及数据传递，也就是 API 的一些设计，通常会相对复杂一些。

我梳理一下我脑袋里面想的 FM 的流程，你看看和你想的是否一致（以网易云音乐 FM 模式为例）：

1. “用户登录“网易云音乐 -> left_panel 弹出”我的音乐/我的电台“选项
![image](https://user-images.githubusercontent.com/4962134/73584469-a7aad380-44d3-11ea-84d1-9f4b93332b1f.png)

2. 用户点击”我的电台“
    1. 播放器就开始进入 fm 模式（需要在 UI 上提示用户）
    2. ...
    3. 网易云音乐插件接收到 eof 信号，去获取”一批电台音乐“？
    4. ...

3. 当一批音乐播放完毕时
    1. ...

这里的第二步和第三步，我感觉需要细化一下，似乎有很多实现方案。

**Comment by cyliuu** [comment]
有一个想法 fm等不一定要放到left_panel（可以放到right_panel）？
理由：
1. 目前各大客户端只有网易云音乐的fm因为功能比较单一在left_panel，其它如QQ音乐和虾米音乐都通过点击left_panel显示在right_panel里了；
2. 目前只有点击本地音乐后right_panel才是有内容反馈的，其它平台点击后right_panel都是没有利用上的，有点浪费。
难度：这样设计的话可能搞定会进一步加大难度，但对扩展其它功能如日推歌曲和日推歌单比较友好

**Comment by wuliaotc** [comment]
**!!!以下FMPlaylist 的含义可能是 feeluown的ui组件 或者一个具体的 _user.fmplaylist 数据,与具体实现有关**

如果不选择playlist来获取新的歌曲,那么就需要实现我之前提到的第二部分的内容

- [ ] 包括特定的left_panel fm listview(可选)

- [ ] 目前current_song只有playlist持有,需要playlist发出eof信号后,由ui部分来获取新的歌曲

- [ ] 需要做ui部分listview与playlist的播放状态的同步 如current_song


>        进入FM mode     
>        1. 播放器就开始进入 fm 模式（需要在 UI 上提示用户）
>        2. playlist 锁定播放顺序;绑定FMPlaylist 不允许修改;获取起初的一批音乐
>        FM mode激活状态下
>        1. playlist 发现剩余歌曲不足,发送eof信号给FMplaylist,由FMPlaylist向provider请求新的歌曲
>        2.如果ui部分实现了FM mode特有的 FMlistview,在点击FMlistviwe内容时,切换播放的歌曲
>        退出FM mode
>        1.除此之外任意add其他歌单的歌曲,都会造成playlist退出FM mode,并且clear playlist后 add歌曲

**Comment by cosven** [comment]
个人观点

> - [ ] 包括特定的left_panel fm listview(可选)

考虑工作量，一开始可以不实现

> - [ ] 目前current_song只有playlist持有,需要playlist发出eof信号后,由FMPlaylist来获取新的歌曲

嗯嗯

> - [ ] 需要做ui部分listview(或者FMPlaylist)与playlist的播放状态的同步 如current_song

这个没有太明白，但直觉这个不影响整体设计。


>进入FM mode     
>   1. 播放器就开始进入 fm 模式（需要在 UI 上提示用户）
>   2. playlist 锁定播放顺序;绑定FMPlaylist 不允许修改;获取起初的一批音乐
>   FM mode激活状态下
>   1. playlist 发现剩余歌曲不足,发送eof信号给FMplaylist,由FMPlaylist向provider请求新的歌曲
>   2.如果ui部分实现了FM mode特有的 FMlistview,在点击FMlistviwe内容时,切换播放的歌曲
>   退出FM mode
>   1.除此之外任意add其他歌单的歌曲,都会造成playlist退出FM mode,并且clear playlist后 add歌曲

这个思路，我感觉大概可以

**Comment by wuliaotc** [comment]
1. 播放器就开始进入 fm 模式（需要在 UI 上提示用户） **进入FM mode**

2. playlist停止播放音乐;playlist清空列表;playlist 锁定播放顺序,底部播放顺序按钮禁止点击;同时FMPlaylist 发送eof信号;将获取的歌曲添加进playlist;开始播放音乐;**FM mode初始化**

3. playlist 发现剩余歌曲不足,发送eof信号给FMplaylist,由FMPlaylist向provider请求新的歌曲 **循环**

4. 如果ui部分实现了FM mode特有的 FMlistview,在点击FMlistviwe内容时,切换播放的歌曲(这里的切换可能会造成playlist发送eof信号) **playlist/FMplaylist内切换歌曲**

5. 用户点击其他歌单或者任意单曲,即playlist接受到任意非FMPlaylist 的add操作,都会造成playlist退出FM mode,并且clear playlist后 add歌曲 **退出FM mode**
