### ISSUE TITLE
提供一个Debian源

### ISSUE THREAD

**Issue by coslyk** [feeluown/FeelUOwn#316]
感谢作者的辛勤付出，提供一个Debian源：https://github.com/coslyk/debianopt-repo

根据页面说明添加源后，可直接通过 `sudo apt install feeluown` 安装。

加油！

**Comment by cosven** [comment]
非常感谢 ~

**Comment by cosven** [comment]
这个方法已经添加到 #313。后续打包相关事项都放在 #313 跟进。
