### ISSUE TITLE
[增强建议]使用系统标准方式查找dll.

### ISSUE THREAD

**Issue by RealXuChe** [feeluown/FeelUOwn#322]
## 简介与背景
Windows安装方式中要把mpv-1.dll放入C:\Windows\System32目录.
恕我直言,这看起来比在Linux下全程用root账户+make install软件还要不安全且难以管理.
## 方案概述
我认为应当使用系统提供的搜索逻辑,或至少使用与系统相同的搜索逻辑,这就会允许用户自己决定dll文件的位置,并进行管理.
根据[ms的文档](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order),查找会在PATH指定的路径中进行.

**Comment by cosven** [comment]
目前查找 DLL 的方式是标准的，只要把 DLL 放到一个系统能搜索到的位置，FeelUOwn 也就能搜索到。安装文档中那样写，是因为这种方式适用于几乎所有的用户。

> 恕我直言,这看起来比在Linux下全程用root账户+make install软件还要不安全且难以管理.

这个问题，我认为确实是存在的。不过我暂时确实不知道有什么更好地方式：即可以让大部分用户（包括“小白”用户）能正常的使用上，又能看起来比较优雅。

欢迎提出好的解决方案 ~

**Comment by RealXuChe** [comment]
写了个小东西来确认加载问题.

```c++
#include "libloaderapi.h"
#include "iostream"
#include "errhandlingapi.h"
using namespace std;

int main(){
    LPCSTR b ="C:\\Programs\\lib\\mpv-1.dll";
    HMODULE a=LoadLibraryA(b);
    cout<< ((a==NULL)?"Loaded":"Not Loaded")<<endl;
    cout<<GetLastError();
}
```

输出是:

```
Not Loaded
0
```

返回值表明加载失败,错误码表示加载成功?????

没搞懂...

这么说这有可能是windows的问题了.(?

**Comment by cosven** [comment]
```c++
cout<< ((a==NULL)?"Loaded":"Not Loaded")<<endl;
```
这个三元表达式写错了把？

**Comment by RealXuChe** [comment]
哦哦哦......    是的.......写反了
(好久没写cpp了

**Comment by cosven** [comment]
> 写了个小东西来确认加载问题.

其实我比较好奇你为什么要写个东西来确认加载问题？是 feeluown 发生了什么错误么？

**Comment by RealXuChe** [comment]
是啊,我没有按照说明指示,而是将mpv-1.dll放在了其他目录.
现在可以确定mpv-1.dll是可以被系统搜索到的,但是fuo却无法加载dll
```
C:\Users\user>python -m feeluown
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\feeluown\__main__.py", line 6, in <module>
    from feeluown.entry_points.run import run
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\feeluown\entry_points\run.py", line 6, in <module>
    from fuocore.utils import is_port_used  # noqa: E402
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fuocore\__init__.py", line 2, in <module>
    from fuocore.player import (
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fuocore\player.py", line 175, in <module>
    from fuocore.mpvplayer import MpvPlayer  # noqa: F841, F401
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fuocore\mpvplayer.py", line 4, in <module>
    from mpv import (
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\mpv.py", line 39, in <module>
    backend = CDLL('mpv-1.dll')
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'mpv-1.dll'. Try using the full path with constructor syntax.
```

**Comment by cosven** [comment]
> 现在可以确定mpv-1.dll是可以被系统搜索到的,但是fuo却无法加载dll

你的测试得不出这个结论把？你的测试程序里面是指定了 `mpv-1.dll` 这个文件的路径，你这样加载，肯定是能加载到。

**Comment by RealXuChe** [comment]
前文没有提及,但是我后来又做了一次测试,没有指定具体路径,也得到了相同的结果.
![图片](https://user-images.githubusercontent.com/47659370/73825235-939a0580-4836-11ea-83fe-56437acf8d5e.png)

**Comment by cosven** [comment]
嗯，后面这个测试还是挺有说服力的。不过还存在一个可疑的点：你的 cpp 程序是在 IDE 里面编译的，需要确认它的环境变量和 cmd 中是否一致。
 
另外，你可以在 cmd 里面用 path 命令看看你的 PATH 是否包含你的 lib 目录。

**Comment by RealXuChe** [comment]
在原程序最后加了一句
```c++
system("path");
```
打印出了环境变量.再与在cmd.exe中执行path命令的结果比对,发现路径完全相同,顺序略有不同.
但是顺序差异并不会影响能否搜索到dll.

lib目录包含在PATH中.

看起来有点像_ctypes的问题了.

**Comment by cosven** [comment]
可以试着运行下面三个命令，来判断 ctypes 是否有问题。
第一个是加载系统 dll
第二个是指定路径，加载系统 dll
第三个是指定路径，加载 mpv-1.dll
第四个是加载 mpv-1.dll
```sh
python -c "from ctypes import CDLL; CDLL('mfcore.dll')"
python -c "from ctypes import CDLL; CDLL('C:\Windows\System32\mfcore.dll')"
python -c "from ctypes import CDLL; CDLL('C:\Programs\lib\mpv-1.dll')"
python -c "from ctypes import CDLL; CDLL('mpv-1.dll')"
```

**Comment by RealXuChe** [comment]
这四条命令的结果符合预期,前三条成功,最后一条失败.
这应该就是ctypes的问题了.
但是搜了一下python issue tracker,没有找到有关issue.
你也在你的电脑上尝试一下以确认吧.

**Comment by RealXuChe** [comment]
看了一下[ctypes文档](https://docs.python.org/3/library/ctypes.html)

> ... otherwise the underlying platforms dlopen or **LoadLibrary function** is used to load the library into the process, and to get a handle to it.

python使用的是LoadLibrary函数.不知道为什么不能找到dll.

**Comment by cosven** [comment]
我通过设置 PATH 环境变量，ctypes 似乎也加载不到。但是放在 system32 是可以的。
所以目前基本可以断定，是 ctypes 看不起 PATH 这个变量，没有用它，具体为什么，还得调查一下。

ps: 如果 cd 到存放 dll 的目录，这样也可以加载：` python -c "from ctypes import CDLL; CDLL('./mpv-1.dll')"`

**Comment by RealXuChe** [comment]
看了下cpython源码.
/Python/dynload_win.c ,line 205就是答案:
```c
hDLL = LoadLibraryExW(wpathname, NULL,
                      LOAD_LIBRARY_SEARCH_DEFAULT_DIRS |
                      LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR);
```
python在win下的搜索路径默认是:python.exe所在目录,system32目录,任何使用AddDllDirectory或SetDllDirectory函数指定的目录.顺序没有担保.

当要加载的dll有依赖时,被依赖项的搜索路径会是:依赖dll所在目录,python.exe所在目录,system32目录,任何使用AddDllDirectory或SetDllDirectory函数指定的目录.顺序没有担保.

结合ctypes文档,可见,python不使用PATH进行搜索,除非在实例化ctypes.PyDLL时通过mode参数指定.

**Comment by cosven** [comment]
刚去看了下 Windows 的接口文档，大概意思类似，不会去搜 PATH 目录：
https://docs.microsoft.com/zh-cn/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexa

**Comment by RealXuChe** [comment]
我建议,在配置文件中允许指定dll路径.

**Comment by cosven** [comment]
> 我建议,在配置文件中允许指定dll路径.

完全可以，欢迎 PR =。=

（也可以之后我来弄这个 ~

**Comment by cosven** [comment]
想了下，最简单的办法是在环境变量里面设置一下 mpv-1.dll 的路径，然后在程序里面读一下。

**Comment by RealXuChe** [comment]
看起来可行,我去试试

**Comment by cosven** [comment]
考虑到每次运行之前都要设置环境变量，这也会很蛋疼。
这时候，可以考虑结合 [`.fuorc` 文件](https://feeluown.readthedocs.io/en/latest/fuorc.html)，在 fuorc 文件里面把这个变量给设置上，就不需要每次运行的时候设置了。

```python
os.environ['MPV_DLL_PATH'] = 'xxx'
```

**Comment by necan** [comment]
其实放到 Python 安装目录也是可以搜索到的。
![image](https://user-images.githubusercontent.com/25315125/73950961-cf68c400-4937-11ea-900d-624b084ea87d.png)

**Comment by RealXuChe** [comment]
为了方便管理,我还是更希望放在统一的文件夹中.
这就是此issue的目的.

**Comment by RealXuChe** [comment]
> 
> 
> 刚去看了下 Windows 的接口文档，大概意思类似，不会去搜 PATH 目录：
> https://docs.microsoft.com/zh-cn/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexa
dll搜索路径的文档在[这里](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order).文档中有写到标准搜索顺序会搜索PATH.

**Comment by albertofwb** [comment]
对于 windows 客户端，何不直接将 mpv-1.dll 放在程序安装目录下呢？

RealXuChe <notifications@github.com> 于2020年2月6日周四 下午11:42写道：

**Comment by RealXuChe** [comment]
程序安装目录就是Python 安装目录吧.......
fuo现在好像没有单独打包二进制

**Comment by RealXuChe** [comment]
Fixed in #325 .
