### ISSUE TITLE
收藏界面专辑显示bug

### ISSUE THREAD

**Issue by cyliuu** [feeluown/FeelUOwn#337]
<img width="1418" alt="WeChatd9fd9bcab3afe358286b5459f323ad1a" src="https://user-images.githubusercontent.com/12897449/74158660-6a71de80-4c55-11ea-9779-d7fe558ffe91.png">
如图所示，专辑右侧留出了一道缝，上下滑动后正常

**Comment by cosven** [comment]
这个现在是不是已经修复了？

**Comment by cyliuu** [comment]
> 这个现在是不是已经修复了？

或许是吧，好久没遇到过了。
