### ISSUE TITLE
Upgrade idna to 2.9?

### ISSUE THREAD

**Issue by tychenjiajun** [feeluown/FeelUOwn#349]

**Comment by cosven** [comment]
ummm，the feeluown project does not limit the version of idna. 

As far as I know, the requests==2.22 limit the idna version to <2.9, but the latest version of requests does not have this constraints.

**Comment by tychenjiajun** [comment]
All of the existing plugins throw errors after upgrading idna to 2.9

**Comment by cosven** [comment]
You may firstly upgrade the requests package to 2.23. After that, you can upgrade idna to 2.9.

Something notable: the latest requets package in douban pypi is 2.22.
