### ISSUE TITLE
Allowing using tsinghua tuna or other pypi mirrors to check latest version?

### ISSUE THREAD

**Issue by tychenjiajun** [feeluown/FeelUOwn#350]

**Comment by cosven** [comment]
Good idea. 

However, we currently depends on the [pypi JSON API](https://wiki.python.org/moin/PyPIJSON). Most of the pypi mirrors do not support this. 

We should also change the way we detect new version if we want to use other pypi mirrors. I think we can add this to TODO list with low priority. If you have some interests in this task and want to PR for this, I'll provide help as much as I can.
