### ISSUE TITLE
[Bug] 私人 FM 极其偶然可能出现重复播放列表的问题

### ISSUE THREAD

**Issue by BruceZhang1993** [feeluown/FeelUOwn#367]
**描述**
私人 FM 极其偶然可能出现重复播放列表的问题

**重现方法**
1. 进入私人 FM 播放
2. 向播放列表添加此前已播放歌曲/私人FM接口提供重复的歌曲
3. 当前歌曲播放结束后未获取 FM 歌曲而是选择列表中的下一首

**预期行为**
当前歌曲播放结束后获取下一首 FM 歌曲

**版本信息**
 - OS: Arch Linux (rolling) x86_64
 - Source: archlinuxcn repository
 - Desktop: KDE 5.18.4 Qt 5.14.2
 - Version: 3.4

**Comment by cosven** [comment]
复现了。当一首歌 url 不正常（bad song）的时候，播放器就不会去获取新歌曲了。

**Comment by BruceZhang1993** [comment]
> 复现了。当一首歌 url 不正常（bad song）的时候，播放器就不会去获取新歌曲了。
> workaround：将播放列表的最后一首歌删除（最后一首是不正常），然后继续播放就好了。

我遇到的好像并不是这样的情况？我是播放到了 FM 模式的历史播放歌曲..

**Comment by cosven** [comment]
我又仔细看了几遍代码，感觉「播放到了 FM 模式的历史播放歌曲」这个逻辑应该是可以正确处理的...

https://github.com/feeluown/FeelUOwn/commit/fd89f333143d8bb601f9c293d5a0bccbd3db0d25
我先修复了我上面说的那种情况。

有空的时候，我手动构造一下有重复歌曲的这种场景。

**Comment by cosven** [comment]
我先把这个 close 了... 等复现的时候再打开吧 ～

**Comment by strit12** [comment]
Sukaa
