### ISSUE TITLE
FeelUOwn v4.0 展望

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#373]
TODO
- [ ] 添加新功能
  - [ ] 支持播放视频
- [ ] 降低提交 PR 的难度，减少抽象层级
  - [x] 放弃 Python 3.5，仅支持 Python 3.6+
  - [ ] fuocore package 提供 App, Playlist, Player, Protocol 等各种类
  - [ ] GUI 相关代码全部放在 feeluown.gui 包里面
- [ ] 新的 model 模型

原则  
1. 关键功能向后兼容。不需要改动已有插件代码，GUI 代码除外。包括 README 中的几个项目。

**Comment by lushuyu** [comment]
可以考虑移植到 Android 或者 iOS 吗？或者说这可能是 v5.0 的 plan 了 ~~（pyqt似乎要收一大笔授权费）~~

**Comment by cosven** [comment]
> 可以考虑移植到 Android 或者 iOS 吗？或者说这可能是 v5.0 的 plan 了 ~（pyqt似乎要收一大笔授权费）~

这里有个安卓版本 https://github.com/BruceZhang1993/FeelUOwnX
大概的思路是将 feeluown 当 proxy 用（daemon 模式），用来访问音乐资源，UI 不使用 feeluown 提供的，另外造一套。

我自己对安卓和 iOS 开发都不熟，所以我只能等有能力有兴趣的同鞋来搞事情，我提供 feeluown 相关的帮助。

**Comment by cosven** [comment]
还是看 roadmap 比较好。
https://feeluown.readthedocs.io/en/latest/roadmap.html
