### ISSUE TITLE
有合适的快捷键设置方法吗

### ISSUE THREAD

**Issue by qqpp4130** [feeluown/FeelUOwn#374]
所以快捷键实现要自己在plasma设置中创建fuo的命令行吗，有没有内建的打算呢？

**Comment by cosven** [comment]
目前支持 multimedia 相关的全局快捷键：上一首，下一首，播放，暂停等。这个是通过 linux 的 mpris2 协议来实现的。

目前没有支持其它「全局快捷键」的计划：
一方面是各个平台的差异很大，所以要完整的支持全局快捷键，会比较困难
另一方面是之前没有收集到相关需求

你这边用全局快捷键主要是想实现什么样的需求或者功能呢？

**Comment by qqpp4130** [comment]
这个只是问一下，老网抑云了，一键喜欢还是挺想实现的
谢谢回复
BTW，应该是没有制作托盘图标后台的想法吧， 虽然daemon实现也不难的样子

**Comment by qqpp4130** [comment]
谢谢大佬费心费力！

**Comment by cosven** [comment]
> 红心按钮还是 TODO 是吧

是的 🙈

> 托盘图标后台

这个其实是有想法的，而且挺想去实现一下的。
