### ISSUE TITLE
请问咋设置本地歌曲扫描目录呀

### ISSUE THREAD

**Issue by grayguest** [feeluown/FeelUOwn#376]
新手上路，没搞明白咋设置，文档中也没提及，另外本地扫描对文件后缀有影响吗？我是在linux下，无后缀的音乐文件。

**Comment by cosven** [comment]
目前只能扫描 `~/Music` 目录下的音乐文件，扫描深度为 2。
如果你的音乐文件不在这个目录，建议创建一个软链接到该目录。

目前只会扫这些后缀 `['mp3', 'ogg', 'wma', 'm4a']`
https://github.com/feeluown/feeluown-local/blob/77ebdb2954298f821388bc9288f4d12d04d52bff/fuo_local/provider.py#L226-L242

如果没有后缀的话，目前建议你给这些文件加上它本来的后缀... 

ps：feeluown-local 插件对本地音乐的支持不是特别的完善。可能需要一些折腾 ~
