### ISSUE TITLE
genicon出错，找不到feeluown.png

### ISSUE THREAD

**Issue by lushuyu** [feeluown/FeelUOwn#377]
不知哪里出了问题。
在安装时我敲的命令是
```bash
pip3 install 'feeluown>=3.0[battery]' --upgrade
```
而不是
```bash
pip3 install 'feeluown>=3.0[battery]' --upgrade --user
```
其它与文档相同。
系统环境：Ubuntu 20.04 LTS
![图片](https://user-images.githubusercontent.com/27007632/85203672-dcfc7480-b341-11ea-8643-58f8c32f6539.png)

~~（应该没什么隐私泄漏吧）~~

**Comment by cosven** [comment]
你之前有没有启动过 FeelUOwn？如果没有启动过，可能会出现这个错误。这算是个 bug。

我看了下代码
https://github.com/feeluown/FeelUOwn/blob/d7a492ca8e44581e7d522ebb4455274f712f1b45/feeluown/install.py#L72-L76

生成桌面图标的时候，程序需要 home 目录下有 `.FeelUOwn` 文件夹，这个文件夹在程序第一次启动后，会自动创建。如果你之前没有运行过程序的话，则可能遇到错误。

推荐手动创建一个 `~/.FeelUOwn` 目录 ~

**Comment by cosven** [comment]
该问题已经在最新版本已经修复。
