### ISSUE TITLE
报错：Please install python package 'qasync'

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#378]
安装了 qasync，没有安装 qt，报如上错误。期望能提示安装 qt。

![image](https://user-images.githubusercontent.com/4962134/85376654-950c6600-b56a-11ea-9dd3-00aabea999e2.png)

这段代码有 bug，qasync 包里面也可能抛出 ImportError。

**Comment by hjlarry** [comment]
感觉直接导入qasync的时候，如未安装qt，它本身就会提示
可能之后去掉compat，其他地方直接从qasync导就行

另外，我的mac是直接在pip中安装PyQt5就行了，好像没必要通过brew等其他方式安装

**Comment by cosven** [comment]
> 感觉直接导入qasync的时候，如未安装qt，它本身就会提示
可能之后去掉compat，其他地方直接从qasync导就行

科学！

> 我的mac是直接在pip中安装PyQt5就行了

我试过通过 pip 来安装 PyQt5，不过会遇到一些奇怪的问题：比如 UI 刷新不及时等。不知道这个现象是否普遍...

**Comment by QQsunny** [comment]
安装了pyqt/pyqt5依然会出现这个please install qasync报错，是不是安装了anaconda导致的？

**Comment by cosven** [comment]
> 安装了pyqt/pyqt5依然会出现这个please install qasync报错，是不是安装了anaconda导致的？

理论上不会受 anaconda 影响。你可以把你的安装方式详细描述一下吗？
你有没有用 miniconda 安装过一部分库，用 pip 也安装过一部分库？
