### ISSUE TITLE
Question:请问,界面d字体如何修改?好像没有用到系统字体.

### ISSUE THREAD

**Issue by wimmerX** [feeluown/FeelUOwn#385]
![image](https://user-images.githubusercontent.com/57867911/89764012-39039e00-db26-11ea-8597-5e42d4390eb4.png)

**Comment by cosven** [comment]
https://github.com/feeluown/FeelUOwn/blob/015ee5fa81469751a08197c0e0854e127d50ed19/feeluown/widgets/magicbox.py#L33

嗯，确实。由于这个框可以输入代码，所以这个输入框使用的是等宽字体。
但理想情况下是：平时是普通字体；只有输入代码时，才使用等宽字体。

你有兴趣修复一下这个问题吗？或者我之后来修复一下也可以。

**Comment by wimmerX** [comment]
yep！ 我试试看。🤓

**Comment by cosven** [comment]
嗯嗯，棒。

为了减少一些看文档花费的时间，我简单说下这一块的逻辑。

当用户输入 `>>> ` 时，我们认为后面的内容就是代码，你可以试试。比如输入 `>>> app.playlist.current_song.title`，这样就能看到当前播放的音乐的标题。这个逻辑对应代码的这个地方。
https://github.com/feeluown/FeelUOwn/blob/015ee5fa81469751a08197c0e0854e127d50ed19/feeluown/widgets/magicbox.py#L115

另外，目前代码里面有个监听文字内容变化的逻辑：
https://github.com/feeluown/FeelUOwn/blob/015ee5fa81469751a08197c0e0854e127d50ed19/feeluown/widgets/magicbox.py#L102-L111

所以，我目前想到的大概的解决思路就是
* 默认设置为普通字体
* 监听到文字**变化**成代码之后，就把字体设置为等宽字体
* 当文字**变化**成普通的内容时，就把字体设置为普通字体

**Comment by wimmerX** [comment]
好的.另外除了输入框之外,界面上的字体是不是也存在这个问题?
![image](https://user-images.githubusercontent.com/57867911/89844947-bb847000-dbaf-11ea-80a3-3e5c842857dc.png)

**Comment by cosven** [comment]
界面上，应该是正常的才对？我在 macOS 上看是正常的。

如果确实不正常的话，可能得看看这些可能性
* 系统上其它 Qt 的字体是否正常
* 有没有给 Qt 应用做一些特殊的配置
* ...（暂时没想到太多可能性）

**Comment by wimmerX** [comment]
其他的能够正常显示.请问FeelUOwn字体配置代码是在哪个位置?

**Comment by cosven** [comment]
目前没有特意给 FeelUOwn 的组件设置字体。

这个字体要么是 Qt 的行为，要么是系统的行为，和 FeelUOwn 关系应该不是很大。

**Comment by wimmerX** [comment]
I see.

**Comment by wimmerX** [comment]
solution :
 os:ubuntu(18.04)
question :使用了Tweak修改系统字体后,FeelUOwn主界面字体没有使用TW设置的字体.

**Comment by wimmerX** [comment]
solution :
os:ubuntu(18.04)
question :使用了Tweak修改系统字体后,FeelUOwn主界面字体没有使用TW设置的字体.

**Comment by wimmerX** [comment]
OS:Ubuntu Bionic Beaver
Question :使用了Tweak修改系统字体后,FeelUOwn主界面字体没有使用TW设置的字体.
Cause :不详.
Solution :`sudo vim /etc/fonts/conf.d/64-language-selector-prefer.conf(eg...using vim/vi)`
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
	<alias>
		<family>sans-serif</family>
		<prefer>
			<family>Noto Sans CJK JP</family>
			<family>Noto Sans CJK SC</family>
			<family>Noto Sans CJK TC</family>
		</prefer>
	</alias>
	<alias>
		<family>monospace</family>
		<prefer>
			<family>Noto Sans Mono CJK JP</family>
			<family>Noto Sans Mono CJK SC</family>
			<family>Noto Sans Mono CJK TC</family>
		</prefer>
	</alias>
</fontconfig>
```
增加/调整预使用字体优先级(同节点,先者优先级高.(tips:系统可能会默认日文为默认首选项).

**Comment by cosven** [comment]
哦哦，原来是中文字体的问题。
