### ISSUE TITLE
search cli outputs empty line for models matching no result

### ISSUE THREAD

**Issue by felixonmars** [feeluown/FeelUOwn#402]
**Describe the bug**
`duo search` outputs an empty line for each model that doesn't return a result.

**To Reproduce**
Run `duo search anything` with duo_local plugin installed and when it matches no song.

![2020-10-13-032254-fadd7f](https://user-images.githubusercontent.com/1006477/95782939-68d84900-0d03-11eb-95ea-e4fdd3df42af.png)

**Expected behavior**
No empty line was present.

**Desktop:**
 - OS: Arch Linux x86_64
 - Version: feeluown 3.5.3

**Additional context**
The problem seems to be in the serializers. When changing https://github.com/feeluown/FeelUOwn/blob/3ebf1086322f229ac0482f35c4df2a8b9f1438ad/fuocore/serializers/plain.py#L109
to `'\n'.join(text for text in text_list if text)` the problem disappears, but I am not sure if this is the right way to fix.

**Comment by cosven** [comment]
https://github.com/feeluown/FeelUOwn/blob/3ebf1086322f229ac0482f35c4df2a8b9f1438ad/fuocore/serializers/plain.py#L107-L109

we should not append empty text to text_list
