### ISSUE TITLE
点击「本地收藏」下的「albums」选单后闪退

### ISSUE THREAD

**Issue by fansuregrin** [feeluown/FeelUOwn#406]
**Describe the bug**
点击「本地收藏」下的「albums」选单后闪退。

**To Reproduce**
1. 打开feeluown软件
2. 点击`本地收藏`下的`albums`
3. 然后闪退

**Expected behavior**

**Screenshots**
![](https://cdn.jsdelivr.net/gh/fansuregrin/imgbed/2020-10-16_16-58.png)

**Desktop:**
 - OS: [Arch Linux x86_64]
 - Kernel: [5.8.14-arch1-1]
 - DE: [Plasma]
 - Version: [feeluown 3.5.3-1]

**Comment by cosven** [comment]
已知问题，在 master 分支已经修复，周末发个新版本 ~

**Comment by fansuregrin** [comment]
好的，谢谢。
