### ISSUE TITLE
在GUI隐藏的情况下歌词窗口获取焦点,会使GUI恢复显示

### ISSUE THREAD

**Issue by wuliaotc** [feeluown/FeelUOwn#413]
**Describe the bug**
在GUI隐藏的情况下歌词窗口获取焦点,会使GUI恢复显示

**To Reproduce**
1. 开启歌词
2. 隐藏GUI到后台
3. 歌词窗口获取焦点

**Expected behavior**
GUI窗口隐藏时,歌词窗口获取焦点,GUI窗口不显示。

**Comment by cosven** [comment]
尝试修复了一下「在GUI隐藏的情况下歌词窗口获取焦点,会使GUI恢复显示」
https://github.com/feeluown/FeelUOwn/commit/b96c767c89faea141b337c0c464a56b326afa43a

另外，顺便把 #414 PR 的内容给合并了
https://github.com/feeluown/FeelUOwn/compare/65c6092e795c667e70ecce5b0c4d28605b0af8b5...c9e4eb157fda779b91b6caa97c6cce2cb5451801

**Comment by cosven** [comment]
备注一下，如果 lyric 窗口类型是
1. Qt.Window，则在任务栏可能出现两个图标
2. Qt.Tooltip，不能接收快捷键
3. Qt.Tool，会随着主窗口一起最小化
