### ISSUE TITLE
下载歌曲功能目前是否可用？

### ISSUE THREAD

**Issue by kqwyf** [feeluown/FeelUOwn#415]
在issues里搜到2016年已经有相关的讨论，并且当时好像已经有实现 #163 。不过目前master版本的软件仍然会提示下载功能未实现。

另外还在 @feeluown 的仓库中找到一个叫做feeluown-download的仓库，看起来是专用于实现下载功能的插件。整体好像有点乱，所以想来问一下下载功能目前的开发情况是怎样的？

**Comment by cosven** [comment]
`feeluown-download` 目前是可以用的，如果确实需要下载功能的话，推荐安装它。
据我所知，目前有一两位童鞋在使用，大体功能是可用的。

不过值得注意的是，它目前功能还比较有限（比如不能设置下载目录，等等），用户体验可能不是特别好。
