### ISSUE TITLE
”音乐提供方“区域没有对齐

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#419]
**Screenshots**
![image](https://user-images.githubusercontent.com/4962134/98879298-2c456c00-24c0-11eb-8c5c-8cc9f4887395.png)

**Comment by cosven** [comment]
解决方案可能有几个
1. 使用 qfontmetrics 让字体对齐
  不过由于这些 charactor 本身大小不一，所以就算加 padding 让宽度一样，也不一定美观，具体效果有待评测
2. 去掉左边的图标
3. 大幅修改 UI，参考 slack 的左侧边栏 🤔

其它方案

1. 使用图标（不是很推荐，图标会极大的增加维护成本）
2. 使用 qpainter 画一个图标（可以考虑，但可能工作量比较大）

**Comment by BruceZhang1993** [comment]
[icons.zip](https://github.com/feeluown/FeelUOwn/files/5676757/icons.zip)

尝试描了一下各个提供方的图标

**Comment by cosven** [comment]
> [icons.zip](https://github.com/feeluown/FeelUOwn/files/5676757/icons.zip)
> 
> 尝试描了一下各个提供方的图标

这些图标是不是主要是给 dark theme 用的？

**Comment by BruceZhang1993** [comment]
> > [icons.zip](https://github.com/feeluown/FeelUOwn/files/5676757/icons.zip)
> > 尝试描了一下各个提供方的图标
> 
> 这些图标是不是主要是给 dark theme 用的？

我记得 SVG 可以调色的，所以就弄了白色的先

**Comment by cosven** [comment]
哦哦，大概了解了。

**Comment by cosven** [comment]
使用 svg icon 后已经没有这个问题。
