### ISSUE TITLE
部分歌词不能正常解析

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#422]
**Describe the bug**

类似这样的歌词目前不能正常解析
```
[xx:xx:xx][xx:xx:xx][xx:xx:xx] 歌词
```

它代表：多个时间点都是这一句歌词。但目前会把 `[xx:xx:xx][xx:xx:xx] 歌词` 都当成歌词。

**Expected behavior**

期望解析成

```
[xx:xx:xx] 歌词
[xx:xx:xx] 歌词
[xx:xx:xx] 歌词
```

**Comment by albertofwb** [comment]
[lyric.py](https://github.com/feeluown/FeelUOwn/blob/master/feeluown/lyric/lyric.py)  参考的[目标代码](https://github.com/osdlyrics/osdlyrics/blob/master/python/lrc.py)中用到了 tokenize 处理了这种情况

**Comment by cosven** [comment]
举个例子：fuo://netease/songs/299966  # 天与地 - 王菲
