### ISSUE TITLE
Chinese input module not working

### ISSUE THREAD

**Issue by MrAru** [feeluown/FeelUOwn#429]
**Describe the bug**
Same as title, the chinese input addon under fcitx5 not working in search box with FeelUOwn.

**To Reproduce**
No special operations are required.
1. Left click to activate search box
2. Change the input method to chinese (which is just not working)

**Desktop:**
 - OS: Manjaro Linux 20.2
 - Version: feeluown 3.6
- Input module: fcitx5, fcitx5-chinese-addons, fcitx5-gtk, fcitx5-qt5 (all of these has been installed)
- Installation source: ArchLinuxCN (`yay -S feeluown-git`)

**Comment by cosven** [comment]
It seems that this case is not related to the `fcitx-frontend-qt5`.

Related issues: https://github.com/feeluown/FeelUOwn/issues/152 https://github.com/feeluown/FeelUOwn/issues/107 https://github.com/feeluown/FeelUOwn/issues/91.

**Comment by MrAru** [comment]
This issue has been resolved. It's probably due to a repackaging for Python 3.9, and the input method is back to normal tonight after Manjaro testing branch update. This is not an issue about FeelUOwn and I'll close this issue. Thanks for helping @cosven .
