### ISSUE TITLE
model 改良的想法收集

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#431]
- 作者：@cosven
- 创建时间：2020-12-08
- 最近更新：2020-12-08 08:30
- 最新状态：
  - *2020-12-08 08:30* - 罗列了当前问题和当前的使用场景

## 要解决的问题

- [ ] model 体系太复杂，属性太多，还有 Stage/ Existence/Display/`create_xxx_g` 等概念
  * 目标：减少概念
- [ ] model.attribute 会自动触发网络请求，容易写出有问题的代码，难 debug
  * 目标：隐式行为尽可能的少
- [ ] 服务方能力和 Model 实例强绑定（比如 Local 提供方支持多种音质，那我们必须实例化一个 LocalSongModel）
  * 目标：解耦 Model 与其能力（能力或许应该与 provider 绑定）

## Model 的常见使用场景

新方案必须能很好地适配以下场景

[文档-媒体资源资源管理](https://feeluown.readthedocs.io/en/stable/media_assets_management.html) 也对下面几个场景进行了相关描述，建议阅读。这里是从使用场景的角度来进行呈现。

###  case1: 展示 model 与获取 model 属性

```python
title_display = song.title_display
real_title = aio.run_inexecutor(None, lambda: song.title)
```

考虑高效展示的需求，我们下了很大的功夫

1. 我们给每个 model 定义为了 display fields
2. 两种实例化的手段：`__init__` 和 `create_by_display`
2. 随之而来的是 model 生命周期：display, init, gotten
3. 考虑到 model 的有效性，我们还创造了 `ModelExistence` 概念

### case2: 可以缓存的属性

```python
class SongModel:
    @field(ttl=3600)
    def url(self):
        pass

song = SongModel()
url = aio.run_in_executor(None, lambda: song.url)
```
问题：明明是属性，但是却要通过 `aio.run_in_executor(None, lambda: song.url)` 这样一串东西来获取

### case3: model 反序列化

```python
line = 'fuo://local/songs/1  # 七里香 - 周杰伦'
model = resolve(line)
title = model.title
```

当前问题：resolve 函数必须返回一个 LocalSongModel
注：我们当前添加了 `provider_added/removed` 信号。配合 `ModelExistence` 属性，可以让 resolve 可以暂时返回一个 SongModel。
目标：resolve 函数理应是无状态的，返回一个标准的 SongModel 即可

### case4: if allow_xxx, then model.xxx

```python
if model.allow_multiple_quality:
    media, q = model.select_media('hq>>>')
else:
    media = model.url
```

问题：allow_xxx 属性太多了
目标：
建议：参考 Qt.WindowFlags 设计

### case5: 模型列表字段的分页

```python
songs_g = model.create_songs_g()
songs_g.read(10)
song_g.read(10)
```

列表类型的字段的数据量可大可小，服务方一般会提供分页的支持。我们设计了 Reader 来进行适配。

**Comment by cosven** [comment]
a simple demo https://gist.github.com/cosven/c36076b7bbe330e5d2fdef5fbd11604f

**Comment by adinlead** [comment]
希望添加webdav支持

**Comment by cosven** [comment]
> 希望添加webdav支持

看起来这个需求和这个 issue 没有什么关系。你可以单独新建个 issue，然后更详细的描述相关需求和使用场景吗？
