### ISSUE TITLE
[MV] As of mpv 0.33.0, opengl-cb API is not working any more

### ISSUE THREAD

**Issue by BruceZhang1993** [feeluown/FeelUOwn#432]
**Describe the bug**
FeelUOwn 目前使用已经废弃 (deprecated) 的 opengl-cb API 渲染 MV
对于 mpv 0.33.0 以上版本的 libmpv opengl-cb 选项已经停用 (deactivated) 且不再正常工作 (not work anymore)

**To Reproduce**
1. 安装 mpv 版本 0.33.0 `mpv --version`
2. 启动 FeelUOwn
3. 播放任意 MV

**Expected behavior**
MV 正常播放

**Desktop:**
 - OS: Arch Linux (rolling)
 - Version: 3.6
- MPV Version: 0.33.0

**Additional context**

> Deprecated opengl-cb API
> An older variant of the render API is called opengl-cb (in libmpv/opengl_cb.h). It is almost equivalent, but is hardcoded to OpenGL and has some other disadvantages. It is deprecated, and you should use libmpv/render.h instead.
> 
> The old API does not work anymore (as of mpv 0.33.0), and was deactivated.

https://github.com/mpv-player/mpv-examples/blob/master/libmpv/README.md

官方建议切换到 libmpv API 需要研究下

**Comment by cosven** [comment]
根据过去的一些调研经验：new-render-context 是 mpv 未来比较推荐的方案，也是可以跨平台的。

可以参考的例子有：
https://github.com/jaseg/python-mpv#using-opengl-from-pyqt5qml-via-new-render-context-api
