### ISSUE TITLE
Standalone instance

### ISSUE THREAD

**Issue by berberman** [feeluown/FeelUOwn#439]
**Describe the bug**
When FeelUOwn is already running in background, trying to launch another instance would cause the new-born one crashed immediately.

**To Reproduce**
1. Launch FeelUOwn
2. Click minimize window
3. Launch FeelUOwn again

**Expected behavior**
FeelUOwn should always run in standalone mode, so its window should be brought back to foreground when creating duplicate instances.

**Screenshots**

https://user-images.githubusercontent.com/26041945/102872553-d11d7680-447a-11eb-84b5-a70295b1476e.mp4

**Desktop:**
 - OS: Arch Linux
 - Version: 3.6.1

**Comment by cosven** [comment]
几个修复思路
1. 在系统层面：不知道在 desktop 文件进行一些设置，能不能达到这种效果 cc @BruceZhang1993 
2. 在 fuo 层面：要让后启动的 fuo 意识到已经有一个实例了，本质应该就是进程间通信
   1. 启动的时候创建一个文件用来标记？
   2. 启动的时候创建一个 socket？
   3. ？？？

**Comment by cosven** [comment]
该问题已经修复，如果有一个实例已经存在，新的实例启动时会弹出一个 UI 框。在非 GUI 模式下，会打一条日志。
