### ISSUE TITLE
Gnome3 下深色主题以及系统托盘问题

### ISSUE THREAD

**Issue by Ninlives** [feeluown/FeelUOwn#448]
**Describe the bug**

1. Gnome3下面黑色主题的显示似乎有点问题（见下截图）
2. Gnome3下面在系统托盘图标右键时菜单一闪就不见了，没有办法退出，只能kill。这个可能是我用的system tray插件的问题（我用的是[tray-icons](https://github.com/zhangkaizhao/gnome-shell-extension-tray-icons)这个插件），是否可以考虑在主界面加一个退出按钮？

**Screenshots**
![image](https://user-images.githubusercontent.com/17873203/105019271-dfae7c00-5a80-11eb-8bd7-abb2f7bbd9b6.png)

**Desktop:**
 - OS: NixOS 21.03 GNOME 3.38.2
 - Version:  feeluown 3.6.1

**Comment by cosven** [comment]
经过在群里的密切沟通，目前已经大概定位了问题的原因以及当下的 workaround，非常感谢。

先说 workaround，如果想要暗色主题，可以在 `~/.fuorc` 文件中配置 
```python
config.THEME = 'macos_dark'
```

**bug1：FeelUOwn 应该自动检测系统主题变化，但实际上并没有**

FeelUOwn 通过读取系统调色盘的颜色来判断系统当前是暗色主题还是亮色主题。经过和 LZ 沟通，发现 LZ 的系统主题（一个 GNOME 主题）为暗色主题，而 FeelUOwn 读到的颜色仍然为亮色，所以 FeelUOwn 误认为系统当前主题为亮色，于是界面主体的背景是亮色的。

而 LZ 在配置文件中配置了 `config.THEME = dark`，所以界面下面受这个配置的影响变成了暗色。

那这个配置为什么没有影响界面的主体呢？这是程序的另外一个 bug。

**bug2：用户配置了 theme 为 dark，但却未完全生效**
FeelUOwn 界面的主体不会受配置 `config.THEME` 影响，它会自己根据系统调色盘来判断。但是界面的下面部分会受这个配置的影响。

**对 bug2 的修复方式**

去掉 dark 以及 light theme，只留下 auto 和 macos_dark theme。

**bug1 的修复方式**
暂时没有想到很好的办法，需要调研。调研主要解决几个问题
1. 调研 GNOME 主题切换后，为什么 QT 读取的调色盘和系统不相符？
2. 调研 GNOME 桌面在切换主题的时候是否会向外部传递信号？
3. ...

**Comment by cosven** [comment]
> 下面在系统托盘图标右键时菜单一闪就不见了，没有办法退出，只能kill

暂时看来和 FeelUOwn 应该没有关系。建议再定位一下根本原因。

> 是否可以考虑在主界面加一个退出按钮

一个 workaround 办法是在搜索框中输入 `>>> app.exit()` 。

**Comment by fearyncess** [comment]
xfce4.16环境下feeluown也会出现右键托盘图标菜单一闪过的问题。

**Comment by fearyncess** [comment]
![x](https://github.com/feeluown/FeelUOwn/blob/b94e212405f1aad30664afbb25170a225e7756ce/feeluown/gui/tray.py#L84)
pdb了一下 发现**右键**点击托盘图标，会直接跳到`self._app.hide()` 然后窗口会直接hide
进一步发现，kde环境下`self._toggle_app_action`被调用了一次，而非KDE环境下被调用了两次，导致主窗体和托盘的右键菜单一次性做了show和hide这两个行为。

**Comment by cosven** [comment]
> 右键托盘图标菜单一闪过的问题

右键一闪而过的意思是说：在托盘图标上右键，然后主界面一闪而过嘛？（看了 @fearyncess 的描述，我感觉是这个意思）。

还是说：在托盘图标上右键，托盘图标一闪而过。（我之前一直都是这么理解的...）

**Comment by cosven** [comment]
> 是不是QSystemTrayIcon在不同托盘实现下的行为问题？

看起来是的。之前就发现在 macOS 上，和 KDE 上有不一样。

**Comment by fearyncess** [comment]
> > 右键托盘图标菜单一闪过的问题
> 
> 右键一闪而过的意思是说：在托盘图标上右键，然后主界面一闪而过嘛？（看了 @fearyncess 的描述，我感觉是这个意思）。
> 
> 还是说：在托盘图标上右键，托盘图标一闪而过。（我之前一直都是这么理解的...）

对的 就是前者要表达的意思

**Comment by cosven** [comment]
根据 issue 的描述，以及 telegram 群里的一些反馈，目前猜测确实是触发了两次 `self._toggle_app_state` 方法。而我们这里是把 _toggle_app_state 方法绑在 activated 信号上，也就是说，QSystemTrayIcon 的 activated 信号被触发了两次。

我后来又去简单查了一些 activated 信号的触发机制，没有发现很多相关资料和 issue。不过看 Qt 的文档，发现 activated 信号触发时，我们可以拿到触发的原因，有三种 [ref](https://doc.qt.io/qt-5/qsystemtrayicon.html#ActivationReason-enum)：
1. unknown
2. The context menu for the system tray entry was requested
3. The system tray entry was double clicked

对应到我们这个 bug 的场景，就是 2。而对于 reason 为 2 时，我们不应该触发 _toggle_app_state。

现在需要明确的有几个点，在某个桌面环境里
1. 左键的时候，activated reason 是什么？右键的时候，activated reason 是否真的是 2？
2. 左键点击的时候，表现是否符合预期（主界面如果本来是隐藏，是否会显示出来；如果本来是显示的，会不会隐藏起来）？

**Comment by fearyncess** [comment]
按左键预期是：如果窗口最小化/隐藏，即显示；如果焦点在窗口时，即隐藏。测试的结果是左键的行为符合预期。
________________________________
发件人: cosven <notifications@github.com>
发送时间: 2021年2月2日 8:25
收件人: feeluown/FeelUOwn <FeelUOwn@noreply.github.com>
抄送: Lain Yang <fsf@live.com>; Mention <mention@noreply.github.com>
主题: Re: [feeluown/FeelUOwn] Gnome3 下深色主题以及系统托盘问题 (#448)


根据 issue 的描述，以及 telegram 群里的一些反馈，目前猜测确实是触发了两次 self._toggle_app_state 方法。而我们这里是把 _toggle_app_state 方法绑在 activated 信号上，也就是说，QSystemTrayIcon 的 activated 信号被触发了两次。

我后来又去简单查了一些 activated 信号的触发机制，没有发现很多相关资料和 issue。不过看 Qt 的文档，发现 activated 信号触发时，我们可以拿到触发的原因，有三种 ref<https://doc.qt.io/qt-5/qsystemtrayicon.html#ActivationReason-enum>：

  1.  unknown
  2.  The context menu for the system tray entry was requested
  3.  The system tray entry was double clicked

对应到我们这个 bug 的场景，就是 2。而对于 reason 为 2 时，我们不应该触发 _toggle_app_state。

现在需要明确的有几个点，在某个桌面环境里

  1.  左键的时候，activated reason 是什么？右键的时候，activated reason 是否真的是 2？
  2.  左键点击的时候，表现是否符合预期（主界面如果本来是隐藏，是否会显示出来；如果本来是显示的，会不会隐藏起来）？

―
