### ISSUE TITLE
顺序播放模式下,播放替代来源的歌曲时,无法自动连播,下一首按钮失效

### ISSUE THREAD

**Issue by Rapiz1** [feeluown/FeelUOwn#450]
**Describe the bug**

顺序播放模式下,播放替代来源的歌曲时,无法自动连播,下一首按钮失效

**To Reproduce**
1. 使用顺序模式
2. 使用网易云来源,非VIP账户,播放一个只含VIP歌曲的歌单,比如 https://music.163.com/#/playlist?id=32008697 
3. 第一首歌曲能正常播放
4. 播放完毕后,不会自动播放下一首
5. 手动点击下一首按钮,没有反应
6. 手动点击其他歌曲的歌曲名,可以播放
7. 播放完毕后 4,5,6 仍然出现

**Expected behavior**
歌单中的歌曲能够自动连播,下一首按钮能够工作

**Screenshots**
not applicable

**Desktop:**
 - OS: Arch Linux
 - Version: feeluown 3.6.1

**Additional context**
stdout log
https://paste.ubuntu.com/p/FN9jPtnM9H/

**Comment by cosven** [comment]
在 master 分支已经修复 ~

**Comment by cosven** [comment]
发了 v3.7.4 ~
