### ISSUE TITLE
歌词配置无法保存

### ISSUE THREAD

**Issue by 1nj0k** [feeluown/FeelUOwn#462]
歌词窗口栏位置，以及字体，字体颜色，背景颜色均无法保存，在退出程序后再次启动程序，均恢复到默认状态。

**Expected behavior**

希望下次启动时可以恢复到之前的配置。

Desktop:

- OS: Arch Linux

- Version: feeluown 3.7.5

**Comment by cosven** [comment]
已经在 3.8.11 版本中修复。
