### ISSUE TITLE
歌曲评论页面 评论作者行高度问题

### ISSUE THREAD

**Issue by yangon99** [feeluown/FeelUOwn#463]
**Describe the bug**
评论页面部分内容高度设置不正确，展示不正常

**Screenshots**
![20210219_1915](https://user-images.githubusercontent.com/54441244/108498273-981d4900-72e7-11eb-9ad1-9cb2f9e5a052.png)

**Desktop:**
 - OS: ArchLinux
 - Version: feeluown 3.7.5
 - Font: Noto Sans

**Comment by cosven** [comment]
根本原因：代码里面硬编码了名字的高度为 15。
https://github.com/feeluown/FeelUOwn/blob/e5f1c22dceeca7c16b551375c24fa22943497d61/feeluown/gui/widgets/comment_list.py#L69-L76

一个解决办法：使用 fontmetrics 算出一个合理的高度

**Comment by cosven** [comment]
#682 中已经解决
