### ISSUE TITLE
字符显示方框+x

### ISSUE THREAD

**Issue by chanceyans** [feeluown/FeelUOwn#464]
![图片](https://user-images.githubusercontent.com/43229885/108501014-9c4b6580-72eb-11eb-8f66-b76e93aea14c.png)
![图片](https://user-images.githubusercontent.com/43229885/108501039-a4a3a080-72eb-11eb-8cf9-413fa7688335.png)

**Comment by yanchongcheng** [comment]
![Uploading 图片.png…]()

**Comment by cosven** [comment]
目前推测是这个字体不能渲染期望的 charactor symbol。

你可以参考这篇博客进行处理吗？如果觉得博客太长，或者直接试试这个配置文件：https://gist.github.com/cosven/a0fae9230d63c4c80646b4e9ca647c0d

**Comment by cosven** [comment]
目前定位为桌面环境的字体配置问题，和 FeelUOwn 本身关系较少，所以先 close。如果你的问题还是没有解决，欢迎 reopen ~
