### ISSUE TITLE
Installation failed: ERROR: You must give at least one requirement to install (see "pip help install")

### ISSUE THREAD

**Issue by Gitorhit** [feeluown/FeelUOwn#468]
**Describe the bug**
Installation bug:

```
==> /usr/local/opt/python@3.9/bin/pip3 install --prefix /usr/local/Cellar/feeluown/3.7.5/libexec
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/feeluown/02.pip3:
2021-03-27 11:04:01 -0700

/usr/local/opt/python@3.9/bin/pip3
install
--prefix
/usr/local/Cellar/feeluown/3.7.5/libexec

ERROR: You must give at least one requirement to install (see "pip help install")
```

**To Reproduce**
On macOS, run: `brew install feeluown/feeluown/feeluown`

**Expected behavior**
Installation successful

**Desktop:**
 - OS: macOS 10.14.6
 - python: 3.9
 - pip: 21.0.1

**Comment by cosven** [comment]
`brew install feeluown/feeluown/feeluown --with-battery` should fix the problem.

**Comment by cosven** [comment]
I have updated the quickstart docs
https://github.com/feeluown/FeelUOwn/commit/1be1a44e331ff076fac051bb027b2fa40964adfa.
Thanks for your bug report.
