### ISSUE TITLE
部分页面不会显示正在播放音乐的音质

### ISSUE THREAD

**Issue by cyliuu** [feeluown/FeelUOwn#469]
**Describe the bug**
如题，具体体现在歌单页面相关数据正常显示且最高音质可以由fuo.rc指定；而在歌手歌曲、专辑歌曲和当前播放列表等页面点击播放的音乐在播放栏相关区域只显示了音乐平台，且相关的音质为实际可以获得的最高音质

**To Reproduce**
从任意方式进入歌手、专辑等页面

**Expected behavior**
在存在多音质时，相关区域应该显示音乐平台+kbps的数据

**Screenshots**
![image](https://user-images.githubusercontent.com/12897449/113480079-195e2300-94c5-11eb-8aae-d8f769c4a505.png)

**Desktop:**
 - OS: any
 - Version: master

**Comment by cosven** [comment]
这个问题在 v3.7.8+ 应该已经被修复了。
