### ISSUE TITLE
video_format的错误信息显示

### ISSUE THREAD

**Issue by cyliuu** [feeluown/FeelUOwn#470]
**Describe the bug**
如题，点击播放音乐每次都会出现关于video_format的错误提示

**To Reproduce**
打开播放器点击播放音乐

**Expected behavior**
相关错误信息消失

**Screenshots**
![image](https://user-images.githubusercontent.com/12897449/113480136-72c65200-94c5-11eb-9016-190581d0c9b2.png)

**Desktop:**
 - OS: MacOS
 - Version: master

**Comment by cosven** [comment]
后续排查发现一个重要的原因是 libmpv 的版本过低，而 FeelUOwn 对老版本的兼容性交叉。
升级 libmpv 到一个较新的版本可以解决。
