### ISSUE TITLE
目前发现的几个问题。

### ISSUE THREAD

**Issue by UEForce** [feeluown/FeelUOwn#490]
Feeluown v3.7.7
fuo-netease v0.6
Python 3.9.4
Gentoo Linux （5.12.9-xanmod1-cacule)

问题如下：
1. 随机模式下点击上一首会自动播放歌单里的第一首歌。
2. 播放进度条几乎不能使用。
3. 有时候一首歌放着放着会突然地切歌。
4. 有时无法搜索。

**Comment by cosven** [comment]
> 随机模式下点击上一首会自动播放歌单里的第一首歌。

是个 bug，我这边也可以复现，我后面去定位一下问题在哪里。

> 播放进度条几乎不能使用。

这个具体是指什么不能用呢？

> 有时候一首歌放着放着会突然地切歌。

这个可以详细的描述一下吗？

> 有时无法搜索。

是指按下 Enter 按钮后，界面上没有反应么？

**Comment by UEForce** [comment]
> > 随机模式下点击上一首会自动播放歌单里的第一首歌。
> 
> 是个 bug，我这边也可以复现，我后面去定位一下问题在哪里。
> 
> > 播放进度条几乎不能使用。
> 
> 这个具体是指什么不能用呢？
> 
> > 有时候一首歌放着放着会突然地切歌。
> 
> 这个可以详细的描述一下吗？
> 
> > 有时无法搜索。
> 
> 是指按下 Enter 按钮后，界面上没有反应么？

1. 关于2中的播放条问题：
     无法拖动播放条，或者拖动了，但无法改变进度。
2. 关于切歌：
      就是说，当正在后台播放一首歌的时候，有时会在没播完的情况下突然自动切换到下一首歌。
3. 搜索的问题与您回复中的描述相符。

**Comment by cosven** [comment]
> 无法拖动播放条，或者拖动了，但无法改变进度。

这个问题，我个人没有遇到过。综合现象来看，目前怀疑是网络环境不佳的情况下，可能会出现，后续我会尝试做一下复现。

> 当正在后台播放一首歌的时候，有时会在没播完的情况下突然自动切换到下一首歌。

这个问题，暂时还没有什么思路，你方便提供这段时间的日志吗？如果能详细的描述一下当时的情况（比如是在播放哪一首歌曲，网络环境如何，界面是否有其他异常）就更好了。

> 搜索的问题与您回复中的描述相符。

网络状况不好时，按下搜索按钮就需要等待比较久，当出现这种情况时，目前界面上没有任何提示，这是一个需要改进的地方。我记一下。

---------------

另外想了解下你这边网络环境怎么样？这三个问题很可能都与网络环境相关。

**Comment by bigshans** [comment]
> > 无法拖动播放条，或者拖动了，但无法改变进度。
> 
> 这个问题，我个人没有遇到过。综合现象来看，目前怀疑是网络环境不佳的情况下，可能会出现，后续我会尝试做一下复现。
> 
> > 当正在后台播放一首歌的时候，有时会在没播完的情况下突然自动切换到下一首歌。
> 
> 这个问题，暂时还没有什么思路，你方便提供这段时间的日志吗？如果能详细的描述一下当时的情况（比如是在播放哪一首歌曲，网络环境如何，界面是否有其他异常）就更好了。
> 
> > 搜索的问题与您回复中的描述相符。
> 
> 网络状况不好时，按下搜索按钮就需要等待比较久，当出现这种情况时，目前界面上没有任何提示，这是一个需要改进的地方。我记一下。
> 
> 另外想了解下你这边网络环境怎么样？这三个问题很可能都与网络环境相关。

进度条应该是组件的问题吧？我这边试了，可以拖动，但点击是无效的。

**Comment by cosven** [comment]
> 可以拖动，但点击是无效的。

目前怀疑这个行为和桌面环境有关系。在 macOS 上是可以的，晚点去 KDE 上测试一下。

**Comment by bigshans** [comment]
> > 可以拖动，但点击是无效的。
> 
> 目前怀疑这个行为和桌面环境有关系。在 macOS 上是可以的，晚点去 KDE 上测试一下。

我个人用的是 KDE ，进度条是有问题的。试了一下 Gnome  ，貌似也出现了这个问题。合理怀疑一下是不是 Linux 下就会出现这个问题。

**Comment by cosven** [comment]
> 我个人用的是 KDE ，进度条是有问题的。试了一下 Gnome ，貌似也出现了这个问题。合理怀疑一下是不是 Linux 下就会出现这个问题。

我试了下 KDE，也是不行的。不过我发现一个有趣的事情，一直点着进度条的某个点不放开，进度条会以定长快进/快退到目标点。

**Comment by cosven** [comment]
小结一下，本 issue 提到四个问题
1. 随机播放模式，点击上一首会播放列表中的第一首歌曲。该问题可以稳定复现，新建 issue 跟进：https://github.com/feeluown/FeelUOwn/issues/512。
2. 第二个进度条的问题，新建 issue 跟进：https://github.com/feeluown/FeelUOwn/issues/513
3. 关于切歌：
就是说，当正在后台播放一首歌的时候，有时会在没播完的情况下突然自动切换到下一首歌。这个在断网的情况也未能复现，需要提供更多的信息。如果该问题还存在，欢迎新建 issue,我们一起来看看 ～
4. 搜索的问题，目前已经有改进，无论搜索是否成功，都会切到搜索页面。后续还有改进空间，比如搜索失败时，弹出通知进行提示。建了一个新 issue 跟进：https://github.com/feeluown/FeelUOwn/issues/513
