### ISSUE TITLE
windows平台上运行feeluown命令出现错误

### ISSUE THREAD

**Issue by aoout** [feeluown/FeelUOwn#498]
**Describe the bug**
在cmd命令中运行feeluown命令出现错误。随后窗口出现，不过行为怪异。

**To Reproduce**

在cmd命令中运行feeluown命令

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/60838705/127739949-2304d356-748d-4b6c-8388-e6d2cf2c94b6.png)

![image](https://user-images.githubusercontent.com/60838705/127739990-70ec1bdd-847e-42f5-9e13-903e8637154b.png)

**Desktop:**
 - OS: 
版本	Windows 11 家庭中文版
Version	21H2
操作系统版本	22000.100
体验	Windows Feature Experience Pack 421.18901.0.3

 - Version: 
 3.7.7

**Additional context**
生成图标后，点击对应的图标的话，不会有任何反应。

**Comment by cosven** [comment]
关于 ModuleNotFound 报错的问题：原因是 pycryptodome 这个库没有安装成功。它的影响是没办法使用网易云音乐插件，其它插件应该可以正常使用。想了解下，你是怎样安装 feeluown 的呢？

关于“行为怪异”，左上角的“音乐提供方”本应出现几个图标的... 日志有提到 Cannot open file，所以图标显示错误了。建议可以尝试盲点“本地音乐”旁边的空白区域试试，或者从搜索歌曲开始。

**Comment by aoout** [comment]
> en f

我尝试了一下，空白区域内是有东西的，只不过图片没有显示。不过为什么图片没有显示呢？我去网上搜索了一下报错信息，可是没有得到解决。

**Comment by cosven** [comment]
尝试在 https://github.com/feeluown/FeelUOwn/commit/6e478bdc6b6033cbb16c94467814ad39c8968ab7 中修复了，但目前还未在 Windows 机器上验证过。

**Comment by aoout** [comment]
> 尝试在 [6e478bd](https://github.com/feeluown/FeelUOwn/commit/6e478bdc6b6033cbb16c94467814ad39c8968ab7) 中修复了，但目前还未在 Windows 机器上验证过。

在我这里没有被解决。我后来自行想办法解决了，是编码问题。不过貌似还是有很多其他问题。这个软件是没什么windows的用户吗？

**Comment by cosven** [comment]
> 我后来自行想办法解决了，是编码问题。

嗯，是编码问题。本来图标的路径是类似 `c:\\Users\\xxx`，经过 QUrl 编码后，变成了`c:%5CUsers%5Cxxx`。所以解决方案是尝试去掉 QURL 编码。

> 这个软件是没什么windows的用户吗？

我知道有一些 windows 用户，但数量没有 Linux 和 macOS 用户多。开发者也主要是在 Linux 和 macOS 环境进行开发。

**Comment by cosven** [comment]
小结一下，这个 issue 之前提到两个问题
1. 一个是 pycryptodome 这个库没有安装。不清楚问题原因是什么，但是理论上安装这个库即可解决。
2. 一个是图标不能正常显示。该问题最新版本已经修复。

由于 issue 有一段时间没有更新了，所以先 close 了。
