### ISSUE TITLE
当前播放列表移除错误

### ISSUE THREAD

**Issue by cyliuu** [feeluown/FeelUOwn#502]
**Describe the bug**
当前播放列表移除错误

**To Reproduce**
移除当前播放列表中的歌曲，每进行一次移除操作 会移除两首歌曲；尝试全部移除时 程序异常退出

**Expected behavior**
正常执行操作逻辑

**Desktop:**
 - OS: Any
 - Version: Any

**Comment by cosven** [comment]
https://github.com/feeluown/FeelUOwn/commit/01bbe7793e40452e3f9e373be0f1fd9066948aba 修复了“每进行一次移除操作 会移除两首歌曲”的问题。

**Comment by cosven** [comment]
测试了一下，目前全选移除和点击清空按钮都不会 crash。 先 close 啦～
