### ISSUE TITLE
'Windows build & release Update to version 3.8.2'  Action 出错

### ISSUE THREAD

**Issue by Veedc** [feeluown/FeelUOwn#554]
https://github.com/feeluown/distribution/runs/4996987763?check_suite_focus=true

>cp -rf build/source/FeelUOwn/feeluown/icons/feeluown.ico build/windows
cp: cannot stat 'build/source/FeelUOwn/feeluown/icons/feeluown.ico': No such file or directory
make: *** [Makefile:31: win64] Error 1
Error: Process completed with exit code 1.`

**Comment by Veedc** [comment]
https://github.com/feeluown/distribution/pull/8
不知 libmpv 既 “mpv-1.dll” 是否需要更新 @cosven

**Comment by cosven** [comment]
mpv-1.dll 暂时不需要更新～
