### ISSUE TITLE
FUO RPC 设计过于开放

### ISSUE THREAD

**Issue by Hill-98** [feeluown/FeelUOwn#560]
这个协议目前设计的是不是过于开放了，居然还有 `exec` 这样的执行任意 Python 代码的命令，而且还没有任何认证机制。

虽然默认监听的是本地地址，谈不上真正意义的远程代码执行，但是也依然有可能被用于远程代码执行。

咱们能不能加个认证机制或者启用选项

**Comment by cosven** [comment]
非常感谢你的反馈 ~

非常认同你的想法，我也觉得它目前存在一定的安全风险。我觉得可以加一个配置（比如 ALLOW_REMOTE_EXEC），默认打开，用户可以在配置里面手动关闭。

p.s. 之前也有开发者提出了相似的问题，当时加了一个“是否允许局域网连接”的配置
https://github.com/feeluown/FeelUOwn/blob/22cd40e92a130165736ce396dfb8c829f33c8465/feeluown/app/config.py#L26

你有兴趣解决一下这个问题嘛？

**Comment by Hill-98** [comment]
我很想解决，但我并不会 Python，不好意思。

我觉得可以加一个认证机制，比如增加个`auth`命令，认证之后才可以执行其他命令。

另外也可以默认情况下不启用 RPC 服务，让用户按需求开启，可以最大程度的保证安全性。
