### ISSUE TITLE
歌词面板漂移现象

### ISSUE THREAD

**Issue by cyliuu** [feeluown/FeelUOwn#563]
**Describe the bug**
RT

**To Reproduce**
当歌词长度超过设定的长度时，歌词会以左边界为固定边，向右边延长 长时间出现歌词面板偏移现象

**Expected behavior**
歌词面板长宽固定，歌词滚动

**Desktop:**
 - OS: macOS
 - Version: matser

**Comment by cosven** [comment]
“歌词滚动”的功能，单独建立了一个 issue：https://github.com/feeluown/FeelUOwn/issues/599 。

歌词面板长度固定的问题，已经在 https://github.com/cosven/FeelUOwn/commit/a4e7ff72cd9f6ff04a133fbb368f350a328d8d8c 中修复了。

**Comment by cosven** [comment]
先把这个 issue 关闭了。

> “歌词滚动”的功能，单独建立了一个 issue：#599 。
> 
> 歌词面板长度固定的问题，已经在 #598 中修复了。
