### ISSUE TITLE
FeelUOwn中QQ音乐插件导致软件闪退问题

### ISSUE THREAD

**Issue by wzcwzc05** [feeluown/FeelUOwn#576]
**问题描述**
平时使用正常，在使用QQ音乐登陆后，软件处于未响应状态或闪退

**环境:**
Archlinux: Kernel: 5.15.28-1-MANJARO 
桌面环境: KDE 5.24.3
Python: 3.10

**问题截图**
![image](https://user-images.githubusercontent.com/41479572/159168064-baba3cc8-a803-4e93-a2a5-0cf01a97c752.png)

![image](https://user-images.githubusercontent.com/41479572/159168046-d3009c65-a01e-4384-8220-f167fc909a87.png)

![image](https://user-images.githubusercontent.com/41479572/159168085-542b4237-795d-4788-9284-8066f4127590.png)

**已尝试过的方式**
1.清除浏览器cookie
2.关闭代理
3.测试域名c.y.qq.com连通性
4.重新安装feeluOwn及插件

**Comment by cosven** [comment]
根据堆栈信息来看，是网络太慢导致出现异常。而代码的这一块异常处理恰好没有，于是应用 Crash 了。

我也尝试本地复现了一下（设置了一个网速很慢的 proxy），然后打开 qq 登陆，报的错几乎一样。但我这边没有崩溃，报错中的栈也有点区别。
![image](https://user-images.githubusercontent.com/4962134/159172426-fbf85b6d-bcca-43de-b1a6-e03332e29d4d.png)
如图，我的是在获取用户信息的时候（api.user_details 接口）报错的，这个是有错误处理的（这个请求在前）。LZ 是在获取用户歌单（user_favorite_playlists）的时候报的错，这个是没有错误处理的（这个请求在后）。 *如果说是 LZ 的网络问题的话，理论上在之前那个请求就会报 Timeout 的错误才对，这一点是比较诡异的。* 

我会把异常处理的逻辑优化一下，避免程序 crash。

至于 LZ 遇到的超时问题，还需要更详细的信息才对判断是什么问题。LZ 可以把 api.py 405-406 行的 timeout 改成 10 试试
![image](https://user-images.githubusercontent.com/4962134/159172792-cdee5867-2e89-416b-947b-5d79faddb820.png)
![image](https://user-images.githubusercontent.com/4962134/159172828-8f9b49c8-4249-446f-bc73-24b8c03dd863.png)
