### ISSUE TITLE
接入系统的媒体播放控制

### ISSUE THREAD

**Issue by reaink** [feeluown/FeelUOwn#591]
![image](https://user-images.githubusercontent.com/45023042/167778500-a08e9fa3-6509-45ea-bd0e-17598587c9d1.png)
如网易云音乐播放器/浏览器 播放媒体时均可在系统控制处见暂停，上/下一曲，也可以用键盘快捷键来切歌暂停

**Comment by BruceZhang1993** [comment]
@reaink 支持

**Comment by cosven** [comment]
Two demos have been implemented. One is written in pyobjc and the other is written in swift.
https://gist.github.com/cosven/22c519d7d82a5c205824d0258dc531a5
https://gist.github.com/cosven/71684e2e08ec07073d418e16cd2dba47

feeluown can't use the pyobjc code directly. One problem is that macOS nowplaying should run with it's own event loop, and it seems the event loop must be run in main thread https://github.com/ronaldoussoren/pyobjc/issues/471.

------------

Another solution is running the pyobjc code in a seperate process. It communicates with feeluown process through RPC and pubsub just like [fust](https://github.com/cosven/fust) does.

**Comment by cosven** [comment]
已经在 #674 中支持。
