### ISSUE TITLE
UI显示问题

### ISSUE THREAD

**Issue by cyliuu** [feeluown/FeelUOwn#603]
**Describe the bug**
1. 歌单显示列表中歌曲序号和播放时间不完整不美观(与之前版本相比)
2. 无法拖动歌曲到列表中
3. 点击播放一首歌似乎触发了三次
4. 本地音乐出现了无法播放的问题(兼容问题)

**Expected behavior**
按照正常逻辑响应

**Desktop:**
 - OS: macOS
 - Version: 3.8.5及之后

**Comment by BruceZhang1993** [comment]
@cyliuu 😳

**Comment by cosven** [comment]
> 1. 歌单显示列表中歌曲序号和播放时间不完整不美观(与之前版本相比)

这个怎么说？

> 3. 点击播放一首歌似乎触发了三次

大概表现为什么？我本地感觉还比较正常。

第 2 点，我也遇到了。后面排查下。
第 4 点，得排查下。

**Comment by cyliuu** [comment]
> > 1. 歌单显示列表中歌曲序号和播放时间不完整不美观(与之前版本相比)
> 
> 这个怎么说？
> 
> > 3. 点击播放一首歌似乎触发了三次
> 
> 大概表现为什么？我本地感觉还比较正常。
> 
> 第 2 点，我也遇到了。后面排查下。 第 4 点，得排查下。

第1点，默认窗口大小时歌曲序号最多支持显示到9，时长显示也不完整：
<img width="651" alt="image" src="https://user-images.githubusercontent.com/12897449/179738028-96c97bfa-42f1-4b4f-950a-ef207bb73488.png"> 

第3点，配合下载插件时 发现点击一次下载 会触发三次下载请求，老版本不会

**Comment by cosven** [comment]
fixed in https://github.com/feeluown/FeelUOwn/pull/611
