### ISSUE TITLE
在比较大的屏幕上歌单等信息无法刷新

### ISSUE THREAD

**Issue by cyliuu** [feeluown/FeelUOwn#633]
**Describe the bug**

**To Reproduce**
使用外接显示器最大化软件，本地音乐的歌手与专辑无法刷新（均伴随不出现滚动条现象）

**Expected behavior**
可以正常刷新

**Screenshots**
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/12897449/207589938-a6f4636d-55b5-4e61-b845-e369bb55ebca.png">
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/12897449/207590016-0ea1488b-1049-48f7-b33d-ca71cfca440f.png">

**Desktop:**
 - OS: macOS
 - Version: master

**Additional context**
目前的本地音乐中的专辑页面的专辑过滤器无法正常切换单曲/EP/专辑等模式，会闪退

**Comment by cosven** [comment]
两个问题
1. 在比较大的屏幕上，歌单等信息无法滚动，从而导致无法刷新。原因是因为 “专辑展示列表” 组件的高度不够高，所以滚动条没有出现，从而无法滚动。修复办法是为 “专辑展示列表” 组件计算一个正确的高度。
2. 闪退的问题：访问了一个错误的字段，应该通过 `album.type_` 来访问专辑类型，而不是 `album.type`。
