### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by tanzihongweb** [feeluown/FeelUOwn#714]
**Describe the bug**
mpv-1.dll 初始化失败,未成功注册
Failed to execute script 'main' due to unhandled exception:
Failed to load dynlib/dll
'mpv-1.dll的路径'Most likely this dynlib/dll was not found when the application was frozen

**To Reproduce**

**Expected behavior**
Enter the program correctly

**Screenshots**
![screencuts2023-07-02#](https://github.com/feeluown/FeelUOwn/assets/109521393/fb7e922f-82ba-4f92-baa6-9edd8c18b273)

**Desktop:**
 - OS: Windows 11 Professional 22H2
 - Version: feeluown 3.8.12

**Additional context**

**Comment by cosven** [comment]
How did you install FeelUOwn? 
Did you download the package(FeelUOwn-windows.zip) from release page directly?

I'll test if the package(FeelUOwn-windows.zip) works later (maybe tonight).

**Comment by tanzihongweb** [comment]
I install from yours github page releases.I cilck .exe to run.
But it's not running on my computer.
Python version:3.11.1
Has this project's python packages

**Comment by cosven** [comment]
BruceZhang1993 also tried to reproduce this problem on win11, and it does not reproduce.

Anyway, sorry for the bad experience :(
