### ISSUE TITLE
歌词窗口关闭自动大小后，位置会自由移动

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#752]
导致的结果是窗口会乱飞
![image](https://github.com/feeluown/FeelUOwn/assets/4962134/ab6e9969-31ec-42bd-a284-4ed6da46d91b)

**Comment by cosven** [comment]
@cosven 目前只在 windows 平台出现过

**Comment by cosven** [comment]
KDE Wayland 没复现
KDE + xorg 也没复现

**Comment by poly000** [comment]
windows 下触发条件：
缩放歌词窗口（必定偏移，移动方向和大小缩减/增加方向相关）
播放歌词时，长句短句
以及过长歌词会导致窗口大小大于屏幕...
