### ISSUE TITLE
暂停/播放/停止 淡入淡出

### ISSUE THREAD

**Issue by poly000** [feeluown/FeelUOwn#762]
- 作者：@xxx 
- 创建时间：2024-01-14
- 最近更新：2024-01-14 21:25
- 最新状态：

## 方案概述

在暂停/播放时，500ms的S曲线音量曲线调整实现淡出/淡入
seek的交叉淡入淡出会更复杂，暂不考虑

曲线：

`(1-cos(pi*tick/time))*(100/2)` 淡入
`(1+cos(pi*tick/time))*(100/2)` 淡出
time为500ms或350ms
tick为设置音量时的时间

精准Timer:

POSIX atimer: windows环境需要使用cygwin编译该包，效果未知
asyncio.sleep: windows下有15ms的精度

**Comment by poly000** [comment]
@poly000 https://en.wikipedia.org/wiki/Fade_(audio_engineering)#Shapes

**Comment by cosven** [comment]
@poly000 停止这样的操作不是瞬时完成么，改成淡入淡出的话，是要把停止的过程延长为几秒钟？
